const fs = require('fs');
const lines = [];
const A = (s) => lines.push(s);

A("'use client'");
A("");
A("import { useState, useEffect, useMemo } from 'react'");
A("import AppShell from '@/components/layout/AppShell'");
A("import Link from 'next/link'");
A("import { useLanguage } from '@/context/LanguageContext'");
A("");
A("const API = process.env.NEXT_PUBLIC_API_URL");
A("");
A("interface Patient {");
A("  id: number");
A("  nom: string");
A("  prenom: string");
A("  diagnostic: string");
A("  numeroDossier: string");
A("  dateNaissance: string");
A("  sexe: string");
A("  statut: string");
A("  dateAdmission: string");
A("  dateDerniereVisite: string");
A("  antecedents: string");
A("}");
A("");
A("export default function ArchivesPage() {");
A("  const { t } = useLanguage()");
A("  const [archives, setArchives]       = useState<Patient[]>([])");
A("  const [loading, setLoading]         = useState(true)");
A("  const [search, setSearch]           = useState('')");
A("  const [confirmId, setConfirmId]     = useState<number | null>(null)");
A("  const [reactivating, setReactivating] = useState<number | null>(null)");
A("");
A("  useEffect(() => {");
A("    fetch(API + '/patients')");
A("      .then(r => r.json())");
A("      .then(data => {");
A("        if (Array.isArray(data)) setArchives(data.filter((p: Patient) => p.statut === 'archive'))");
A("      })");
A("      .catch(() => {})");
A("      .finally(() => setLoading(false))");
A("  }, [])");
A("");
A("  async function reactiver(id: number) {");
A("    setReactivating(id)");
A("    try {");
A("      await fetch(API + '/patients/' + id, {");
A("        method: 'PATCH',");
A("        headers: { 'Content-Type': 'application/json' },");
A("        body: JSON.stringify({ statut: 'actif' })");
A("      })");
A("      setArchives(prev => prev.filter(p => p.id !== id))");
A("    } catch {}");
A("    setReactivating(null)");
A("    setConfirmId(null)");
A("  }");
A("");
A("  const filtered = useMemo(() => {");
A("    if (!search.trim()) return archives");
A("    const s = search.toLowerCase()");
A("    return archives.filter(p =>");
A("      p.nom?.toLowerCase().includes(s) ||");
A("      p.prenom?.toLowerCase().includes(s) ||");
A("      p.diagnostic?.toLowerCase().includes(s) ||");
A("      p.numeroDossier?.toLowerCase().includes(s)");
A("    )");
A("  }, [search, archives])");
A("");
A("  return (");
A("    <AppShell searchPlaceholder={t('arc_rechercherPlaceholder')} showSearch={false}>");
A("      <div className=\"flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4 mb-6\">");
A("        <div>");
A("          <h2 className=\"text-2xl font-bold text-on-surface font-manrope\">{t('arc_titre')}</h2>");
A("          <p className=\"text-sm text-on-surface-variant mt-1\">{archives.length} {t('arc_dossiersArchives')}</p>");
A("        </div>");
A("        <div className=\"flex items-center gap-3 bg-surface border border-outline-variant px-4 py-2 rounded-lg max-w-sm\">");
A("          <span className=\"material-symbols-outlined text-on-surface-variant text-lg\">search</span>");
A("          <input type=\"text\" placeholder={t('arc_rechercherPlaceholder')}");
A("            value={search} onChange={e => setSearch(e.target.value)}");
A("            className=\"bg-transparent border-none focus:outline-none text-sm w-full text-on-surface placeholder:text-on-surface-variant\" />");
A("          {search && (");
A("            <button onClick={() => setSearch('')} className=\"text-on-surface-variant hover:text-red-500 transition-colors\">");
A("              <span className=\"material-symbols-outlined text-lg\">close</span>");
A("            </button>");
A("          )}");
A("        </div>");
A("      </div>");
A("");
A("      {loading ? (");
A("        <div className=\"flex flex-col items-center justify-center py-24 text-on-surface-variant\">");
A("          <div className=\"w-10 h-10 border-4 border-primary border-t-transparent rounded-full animate-spin mb-4\"></div>");
A("          <p className=\"text-sm\">{t('arc_chargement')}</p>");
A("        </div>");
A("      ) : (");
A("        <>");
A("          <div className=\"space-y-4\">");
A("            {filtered.map((p) => (");
A("              <div key={p.id} className=\"card p-5 hover:shadow-md transition-shadow\">");
A("                <div className=\"flex flex-col sm:flex-row gap-4\">");
A("");
A("                  <div className=\"flex-shrink-0 sm:w-56\">");
A("                    <div className=\"flex items-center gap-3 mb-2\">");
A("                      <div className=\"w-10 h-10 rounded-full bg-surface-container-low flex items-center justify-center\">");
A("                        <span className=\"text-on-surface-variant font-bold text-sm\">{p.prenom?.[0]}{p.nom?.[0]}</span>");
A("                      </div>");
A("                      <div>");
A("                        <Link href={'/patients/' + p.id + '?from=archives'}");
A("                          className=\"font-semibold text-on-surface text-sm hover:text-primary transition-colors\">");
A("                          {p.prenom} {p.nom}");
A("                        </Link>");
A("                        <p className=\"text-[10px] text-on-surface-variant\">{p.numeroDossier}</p>");
A("                      </div>");
A("                    </div>");
A("                    <p className=\"text-xs text-on-surface-variant\">{p.diagnostic || '-'}</p>");
A("                  </div>");
A("");
A("                  <div className=\"flex-1 border-l border-outline-variant pl-4\">");
A("                    <div className=\"flex items-center gap-2 mb-2\">");
A("                      <span className=\"w-2 h-2 rounded-full bg-red-400\" />");
A("                      <span className=\"text-xs text-on-surface-variant uppercase tracking-wider\">");
A("                        {t('arc_archiveAdmission')} {p.dateAdmission || '-'}");
A("                      </span>");
A("                    </div>");
A("                    <p className=\"text-xs text-on-surface-variant leading-relaxed mb-2\">");
A("                      {p.antecedents || t('arc_aucunAntecedent')}");
A("                    </p>");
A("                    <div className=\"flex items-center gap-2 mt-2\">");
A("                      <span className=\"text-[10px] bg-surface-container-low text-on-surface-variant px-2 py-1 rounded uppercase tracking-wider\">");
A("                        {p.sexe === 'M' ? t('cal_homme') : p.sexe === 'F' ? t('cal_femme') : '-'}");
A("                      </span>");
A("                      <span className=\"text-[10px] bg-surface-container-low text-on-surface-variant px-2 py-1 rounded uppercase tracking-wider\">");
A("                        {p.dateNaissance || '-'}");
A("                      </span>");
A("                    </div>");
A("                  </div>");
A("");
A("                  <div className=\"flex-shrink-0 flex items-center gap-2\">");
A("                    <button onClick={() => setConfirmId(p.id)}");
A("                      className=\"inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-50 text-emerald-700 text-xs font-semibold hover:bg-emerald-100 transition-colors border border-emerald-200\">");
A("                      <span className=\"material-symbols-outlined text-sm\">person_check</span>");
A("                      {t('arc_btnReactiver')}");
A("                    </button>");
A("                    <Link href={'/patients/' + p.id + '?from=archives'}");
A("                      className=\"p-2 rounded-lg hover:bg-surface-container-low transition-colors\" title={t('arc_voirProfil')}>");
A("                      <span className=\"material-symbols-outlined text-on-surface-variant text-lg\">visibility</span>");
A("                    </Link>");
A("                  </div>");
A("");
A("                </div>");
A("              </div>");
A("            ))}");
A("          </div>");
A("");
A("          {filtered.length === 0 && (");
A("            <div className=\"py-12 text-center text-on-surface-variant\">");
A("              <span className=\"material-symbols-outlined text-4xl mb-2\">inventory_2</span>");
A("              <p>{search ? t('arc_aucunResultat') : t('arc_aucunArchive')}</p>");
A("              {search && (");
A("                <button onClick={() => setSearch('')}");
A("                  className=\"mt-4 px-4 py-2 rounded-lg bg-primary text-white text-sm font-semibold hover:opacity-90\">");
A("                  {t('arc_voirTousArchives')}");
A("                </button>");
A("              )}");
A("            </div>");
A("          )}");
A("        </>");
A("      )}");
A("");
A("      {confirmId !== null && (");
A("        <div className=\"fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm\">");
A("          <div className=\"bg-surface rounded-2xl shadow-2xl p-8 max-w-sm w-full mx-4 text-center\">");
A("            <div className=\"w-16 h-16 bg-emerald-50 rounded-full flex items-center justify-center mx-auto mb-4\">");
A("              <span className=\"material-symbols-outlined text-emerald-500 text-3xl\">person_check</span>");
A("            </div>");
A("            <h3 className=\"text-lg font-bold text-on-surface mb-2\">{t('arc_modalTitre')}</h3>");
A("            <p className=\"text-sm text-on-surface-variant mb-6\">");
A("              {t('arc_modalDescAvant')} <strong>Actif</strong> {t('arc_modalDescApres')}");
A("            </p>");
A("            <div className=\"flex gap-3\">");
A("              <button onClick={() => setConfirmId(null)}");
A("                className=\"flex-1 px-4 py-2.5 rounded-lg border border-outline-variant text-on-surface font-semibold text-sm hover:bg-surface-container-low\">");
A("                {t('arc_annuler')}");
A("              </button>");
A("              <button onClick={() => reactiver(confirmId)}");
A("                disabled={reactivating === confirmId}");
A("                className=\"flex-1 px-4 py-2.5 rounded-lg bg-emerald-500 text-white font-semibold text-sm hover:bg-emerald-600 shadow-sm disabled:opacity-60\">");
A("                {reactivating === confirmId ? t('arc_enCours') : t('arc_confirmer')}");
A("              </button>");
A("            </div>");
A("          </div>");
A("        </div>");
A("      )}");
A("");
A("    </AppShell>");
A("  )");
A("}");

fs.writeFileSync('D:/chu_kine/projet_frontend/src/app/archives/page.tsx', lines.join('\n'), {encoding:'utf8'});
console.log('archives/page.tsx traduit avec succes !');
