const fs = require('fs');
const lines = [];
const A = (s) => lines.push(s);

A("'use client'");
A("");
A("import Link from 'next/link'");
A("import AppShell from '@/components/layout/AppShell'");
A("import { useLanguage } from '@/context/LanguageContext'");
A("");
A("const appointments = [");
A("  { id: 1, patientId: 101, time: '09:00', period: 'AM', name: 'Sarah Jenkins', motif: 'Suivi Post-operatoire - Genou', initials: 'SJ', avatarBg: 'bg-teal-100 text-teal-700' },");
A("  { id: 2, patientId: 102, time: '10:30', period: 'AM', name: 'Michael Chen', motif: 'Consultation Initial - Dos', initials: 'MC', avatarBg: 'bg-blue-100 text-blue-700' },");
A("  { id: 3, patientId: 103, time: '02:15', period: 'PM', name: 'Elena Rodriguez', motif: 'Reeducation - Epaule', initials: 'ER', avatarBg: 'bg-cyan-100 text-cyan-700' },");
A("]");
A("");
A("export default function DashboardPage() {");
A("  const { t } = useLanguage()");
A("");
A("  return (");
A("    <AppShell searchPlaceholder=\"Rechercher un patient, un dossier...\">");
A("");
A("      {/* EN-TETE */}");
A("      <div className=\"mb-8\">");
A("        <h2 className=\"text-4xl font-extrabold text-on-surface tracking-tight\">{t('dash_bonjour')}</h2>");
A("        <p className=\"font-body-lg text-on-surface-variant mt-1\">{t('dash_apercu')}</p>");
A("      </div>");
A("");
A("      {/* RDV DU JOUR (liste mock) */}");
A("      <div className=\"bg-surface rounded-xl border border-outline-variant shadow-sm overflow-hidden\">");
A("        <div className=\"px-6 py-4 border-b border-outline-variant flex justify-between items-center bg-surface-container-low/50\">");
A("          <h4 className=\"font-title-sm text-on-surface\">{t('dash_rdvDuJour')}</h4>");
A("          <Link href=\"/calendrier\" className=\"text-primary font-semibold text-sm hover:underline\">{t('dash_voirTout')}</Link>");
A("        </div>");
A("        <div className=\"divide-y divide-outline-variant\">");
A("          {appointments.map((appt) => (");
A("            <Link key={appt.id} href={'/patients/' + appt.patientId + '?from=dashboard'}");
A("              className=\"px-6 py-5 flex items-center gap-4 hover:bg-surface-container-low transition-colors\">");
A("              <div className=\"text-center min-w-[60px]\">");
A("                <p className=\"text-xs font-bold tracking-widest uppercase text-primary\">{appt.time}</p>");
A("                <p className=\"text-xs text-on-surface-variant\">{appt.period}</p>");
A("              </div>");
A("              <div className={'w-12 h-12 rounded-full flex items-center justify-center flex-shrink-0 font-bold text-sm ' + appt.avatarBg}>");
A("                {appt.initials}");
A("              </div>");
A("              <div className=\"flex-1\">");
A("                <p className=\"font-semibold text-on-surface\">{appt.name}</p>");
A("                <p className=\"text-sm text-on-surface-variant\">{appt.motif}</p>");
A("              </div>");
A("              <span className=\"material-symbols-outlined text-on-surface-variant text-lg flex-shrink-0\">chevron_right</span>");
A("            </Link>");
A("          ))}");
A("        </div>");
A("      </div>");
A("");
A("    </AppShell>");
A("  )");
A("}");

fs.writeFileSync('D:/chu_kine/projet_frontend/src/app/page.tsx', lines.join('\n'), {encoding:'utf8'});
console.log('Dashboard mis a jour - cadre RDV retire !');
