const fs = require('fs');
const lines = [];
const A = (s) => lines.push(s);

A("'use client'");
A("");
A("import { useState, useEffect } from 'react'");
A("import { useSearchParams } from 'next/navigation'");
A("import Link from 'next/link'");
A("import { useRouter } from 'next/navigation'");
A("import AppShell from '@/components/layout/AppShell'");
A("");
A("const API = process.env.NEXT_PUBLIC_API_URL");
A("");
A("interface Patient {");
A("  id: number; numeroDossier: string; nom: string; prenom: string");
A("  dateNaissance: string; sexe: string; adresse: string; telephone: string");
A("  diagnostic: string; statut: string; dateAdmission: string");
A("  dateDerniereVisite: string; antecedents: string");
A("}");
A("");
A("interface HistoriqueEntry { date: string; heure: string; texte: string }");
A("");
A("const MOCK_PATIENTS: Record<number, Patient> = {");
A("  1:   { id: 1,   numeroDossier: 'P-2024-001', nom: 'Rakoto', prenom: 'Jean', dateNaissance: '1985-03-12', sexe: 'M', adresse: 'Fianarantsoa', telephone: '+261 34 00 000 01', diagnostic: 'Rupture LCA genou droit', statut: 'actif', dateAdmission: '2024-04-12', dateDerniereVisite: '2024-06-08', antecedents: 'Aucun antecedent' },");
A("  2:   { id: 2,   numeroDossier: 'P-2024-002', nom: 'Rabe', prenom: 'Marie', dateNaissance: '1992-07-23', sexe: 'F', adresse: 'Fianarantsoa', telephone: '+261 34 00 000 02', diagnostic: 'Tendinite calcifiante epaule droite', statut: 'actif', dateAdmission: '2024-04-18', dateDerniereVisite: '2024-06-05', antecedents: 'Aucun antecedent' },");
A("  3:   { id: 3,   numeroDossier: 'P-2024-003', nom: 'Andria', prenom: 'Paul', dateNaissance: '1978-11-08', sexe: 'M', adresse: 'Fianarantsoa', telephone: '+261 34 00 000 03', diagnostic: 'Entorse cheville gauche grade 2', statut: 'actif', dateAdmission: '2024-04-22', dateDerniereVisite: '2024-06-09', antecedents: 'Aucun antecedent' },");
A("  4:   { id: 4,   numeroDossier: 'P-2024-004', nom: 'Rasoa', prenom: 'Lala', dateNaissance: '1965-05-30', sexe: 'F', adresse: 'Fianarantsoa', telephone: '+261 34 00 000 04', diagnostic: 'Arthrose lombaire chronique', statut: 'actif', dateAdmission: '2024-05-02', dateDerniereVisite: '', antecedents: 'Aucun antecedent' },");
A("  5:   { id: 5,   numeroDossier: 'P-2024-005', nom: 'Rakotonirina', prenom: 'Zo', dateNaissance: '2001-09-15', sexe: 'F', adresse: 'Fianarantsoa', telephone: '+261 34 00 000 05', diagnostic: 'Scoliose thoracique', statut: 'inactif', dateAdmission: '2024-03-10', dateDerniereVisite: '2024-05-28', antecedents: 'Aucun antecedent' },");
A("  6:   { id: 6,   numeroDossier: 'P-2024-006', nom: 'Randriamihaingo', prenom: 'Tiana', dateNaissance: '1988-02-20', sexe: 'F', adresse: 'Fianarantsoa', telephone: '+261 34 00 000 06', diagnostic: 'Paralysie faciale peripherique droite', statut: 'en_attente', dateAdmission: '2024-06-08', dateDerniereVisite: '', antecedents: 'Aucun antecedent' },");
A("  101: { id: 101, numeroDossier: 'P-2024-101', nom: 'Jenkins', prenom: 'Sarah', dateNaissance: '1990-05-14', sexe: 'F', adresse: 'Fianarantsoa', telephone: '+261 34 00 001 01', diagnostic: 'Suivi Post-operatoire Genou', statut: 'actif', dateAdmission: '2024-03-01', dateDerniereVisite: '2024-06-10', antecedents: 'Operation genou droit mars 2024' },");
A("  102: { id: 102, numeroDossier: 'P-2024-102', nom: 'Chen', prenom: 'Michael', dateNaissance: '1983-11-22', sexe: 'M', adresse: 'Fianarantsoa', telephone: '+261 34 00 001 02', diagnostic: 'Consultation Initial Dos', statut: 'en_attente', dateAdmission: '2024-06-09', dateDerniereVisite: '', antecedents: 'Douleurs lombaires chroniques' },");
A("  103: { id: 103, numeroDossier: 'P-2024-103', nom: 'Rodriguez', prenom: 'Elena', dateNaissance: '1981-03-08', sexe: 'F', adresse: 'Fianarantsoa', telephone: '+261 34 00 001 03', diagnostic: 'Reeducation Epaule', statut: 'actif', dateAdmission: '2024-04-15', dateDerniereVisite: '2024-06-12', antecedents: 'Rupture partielle coiffe des rotateurs' },");
A("}");
A("");
A("function getNow() {");
A("  const now = new Date()");
A("  const date = now.getDate() + ' ' + now.toLocaleDateString('fr-FR',{month:'long'}) + ' ' + now.getFullYear()");
A("  const heure = String(now.getHours()).padStart(2,'0') + 'h' + String(now.getMinutes()).padStart(2,'0')");
A("  return { date, heure }");
A("}");
A("");
A("const TYPES = ['consultation','bilan','soin','exercice']");
A("const TYPE_COLOR: Record<string,string> = {");
A("  consultation: 'bg-teal-100 text-teal-700 border-teal-300',");
A("  bilan:        'bg-purple-100 text-purple-700 border-purple-300',");
A("  soin:         'bg-blue-100 text-blue-700 border-blue-300',");
A("  exercice:     'bg-amber-100 text-amber-700 border-amber-300',");
A("}");
A("");
A("function ChampLibre({ label, value, onChange, placeholder, icon, rows=3, locked=false }: {");
A("  label: string; value: string; onChange: (v:string)=>void");
A("  placeholder?: string; icon?: string; rows?: number; locked?: boolean");
A("}) {");
A("  return (");
A("    <div>");
A("      <label className=\"text-xs font-bold text-slate-400 uppercase tracking-widest block mb-1 flex items-center gap-1\">");
A("        {icon && <span className=\"material-symbols-outlined text-sm text-primary\">{icon}</span>}");
A("        {label}");
A("      </label>");
A("      <textarea value={value} onChange={e => !locked && onChange(e.target.value)} rows={rows}");
A("        disabled={locked}");
A("        className={'w-full p-3 rounded-lg border text-sm resize-none outline-none transition-all ' + (locked ? 'bg-slate-100 border-slate-200 text-slate-500 cursor-not-allowed' : 'bg-slate-50 border-slate-200 focus:border-primary focus:ring-1 focus:ring-primary')}");
A("        placeholder={locked ? '' : (placeholder || 'Saisir...')} />");
A("    </div>");
A("  )");
A("}");
A("");
A("function SectionHistorique({ label, icon, value, onChange, historique, onEnregistrer, colorClass='bg-slate-50 border-slate-100', timeClass='text-slate-400', locked=false }: {");
A("  label: string; icon: string; value: string; onChange: (v:string)=>void");
A("  historique: HistoriqueEntry[]; onEnregistrer: ()=>void");
A("  colorClass?: string; timeClass?: string; locked?: boolean");
A("}) {");
A("  return (");
A("    <div className=\"bg-white rounded-xl shadow-sm border border-slate-200 p-6\">");
A("      <h3 className=\"font-headline-md text-on-surface flex items-center gap-2 mb-4\">");
A("        <span className=\"material-symbols-outlined text-primary\">{icon}</span>");
A("        {label}");
A("        {locked && <span className=\"ml-auto text-xs bg-emerald-50 text-emerald-600 px-2 py-0.5 rounded-full font-semibold flex items-center gap-1\"><span className=\"material-symbols-outlined text-sm\">lock</span>Validé</span>}");
A("      </h3>");
A("      {!locked && (");
A("        <div className=\"relative mb-3\">");
A("          <textarea value={value} onChange={e => onChange(e.target.value)} rows={3}");
A("            className=\"w-full p-4 rounded-lg bg-slate-50 border border-slate-200 focus:border-primary focus:ring-1 focus:ring-primary text-sm resize-none outline-none pb-12\"");
A("            placeholder={'Saisir ' + label.toLowerCase() + '...'} />");
A("          <div className=\"absolute bottom-3 right-3\">");
A("            <button onClick={onEnregistrer}");
A("              className=\"bg-primary text-white px-4 py-1.5 rounded-lg text-sm font-semibold shadow hover:opacity-90 transition\">");
A("              Enregistrer");
A("            </button>");
A("          </div>");
A("        </div>");
A("      )}");
A("      {historique.length > 0 && (");
A("        <div className=\"mt-3 space-y-2\">");
A("          <p className=\"text-xs font-bold text-slate-400 uppercase tracking-widest\">Historique</p>");
A("          {historique.map((h, i) => (");
A("            <div key={i} className={'rounded-lg p-3 border ' + colorClass}>");
A("              <p className={'text-[10px] font-semibold mb-1 ' + timeClass}>{h.date} — {h.heure}</p>");
A("              <p className=\"text-sm text-on-surface\">{h.texte}</p>");
A("            </div>");
A("          ))}");
A("        </div>");
A("      )}");
A("      {historique.length === 0 && locked && (");
A("        <p className=\"text-sm text-slate-400 italic\">Aucune entrée enregistrée</p>");
A("      )}");
A("    </div>");
A("  )");
A("}");
A("");
A("export default function PatientProfilePage({ params }: { params: { id: string } }) {");
A("  const [patient, setPatient]   = useState<Patient | null>(null)");
A("  const [loading, setLoading]   = useState(true)");
A("  const [valide, setValide]     = useState(false)");
A("  const [showConfirm, setShowConfirm] = useState(false)");
A("  const searchParams = useSearchParams()");
A("  const router = useRouter()");
A("  const from = searchParams.get('from')");
A("");
A("  // Seance du jour");
A("  const [heureDebut, setHeureDebut]     = useState('')");
A("  const [heureFin, setHeureFin]         = useState('')");
A("  const [typeRdv, setTypeRdv]           = useState('')");
A("  const [showTypeMenu, setShowTypeMenu] = useState(false)");
A("");
A("  // Etat civil");
A("  const [religion, setReligion] = useState('')");
A("");
A("  // Admission");
A("  const [modeAdmission, setModeAdmission] = useState('')");
A("  const [autoRefere, setAutoRefere]       = useState('')");
A("  const [referePar, setReferePar]         = useState('')");
A("");
A("  // Objectif");
A("  const [objectif, setObjectif] = useState('')");
A("");
A("  // Bilan kine");
A("  const [antecedents, setAntecedents]           = useState('')");
A("  const [historieMaladie, setHistorieMaladie]   = useState('')");
A("  const [bilanFonctionnel, setBilanFonctionnel] = useState('')");
A("  const [bilanIncapacite, setBilanIncapacite]   = useState('')");
A("");
A("  // Diagnostic kine");
A("  const [diagnosticKine, setDiagnosticKine] = useState('')");
A("");
A("  // Traitement");
A("  const [traitement, setTraitement] = useState('')");
A("  const [historiqueTraitement, setHistoriqueTraitement] = useState<HistoriqueEntry[]>([])");
A("");
A("  // Evolution");
A("  const [evolution, setEvolution] = useState('')");
A("  const [historiqueEvolution, setHistoriqueEvolution] = useState<HistoriqueEntry[]>([])");
A("");
A("  // Conseil");
A("  const [conseil, setConseil] = useState('')");
A("");
A("  useEffect(() => {");
A("    const numId = parseInt(params.id)");
A("    if (MOCK_PATIENTS[numId]) {");
A("      setPatient(MOCK_PATIENTS[numId])");
A("      setAntecedents(MOCK_PATIENTS[numId].antecedents || '')");
A("      setLoading(false)");
A("      return");
A("    }");
A("    fetch(API + '/patients/' + params.id)");
A("      .then(r => r.json())");
A("      .then(data => { if (data?.id) { setPatient(data); setAntecedents(data.antecedents || '') } setLoading(false) })");
A("      .catch(() => setLoading(false))");
A("  }, [params.id])");
A("");
A("  function enregistrer(texte: string, setTexte: (v:string)=>void, setHisto: React.Dispatch<React.SetStateAction<HistoriqueEntry[]>>) {");
A("    if (!texte.trim()) return");
A("    const { date, heure } = getNow()");
A("    setHisto(prev => [{ date, heure, texte }, ...prev])");
A("    setTexte('')");
A("  }");
A("");
A("  function confirmerValidation() {");
A("    setValide(true)");
A("    setShowConfirm(false)");
A("    setTimeout(() => router.push('/rapport'), 1500)");
A("  }");
A("");
A("  if (loading) return (");
A("    <AppShell searchPlaceholder=\"Rechercher...\">");
A("      <div className=\"py-24 text-center text-on-surface-variant\">");
A("        <span className=\"material-symbols-outlined text-5xl animate-spin\">progress_activity</span>");
A("        <p className=\"mt-4\">Chargement du profil...</p>");
A("      </div>");
A("    </AppShell>");
A("  )");
A("");
A("  if (!patient) return (");
A("    <AppShell searchPlaceholder=\"Rechercher...\">");
A("      <div className=\"py-24 text-center text-on-surface-variant\">");
A("        <span className=\"material-symbols-outlined text-5xl\">person_off</span>");
A("        <p className=\"mt-4\">Patient introuvable</p>");
A("        <Link href=\"/patients\" className=\"mt-4 inline-block text-primary hover:underline\">Retour a la liste</Link>");
A("      </div>");
A("    </AppShell>");
A("  )");
A("");
A("  const initials = (patient.prenom?.[0] || '') + (patient.nom?.[0] || '')");
A("  const nomComplet = patient.prenom + ' ' + patient.nom");
A("");
A("  return (");
A("    <AppShell searchPlaceholder=\"Rechercher un patient...\">");
A("");
A("      {/* Fil d ariane */}");
A("      <nav className=\"flex items-center gap-2 text-sm text-on-surface-variant mb-6\">");
A("        {from === 'archives' ? (<><Link href=\"/archives\" className=\"hover:text-primary\">Archives</Link><span className=\"material-symbols-outlined text-sm\">chevron_right</span><span className=\"text-on-surface font-semibold\">{nomComplet}</span></>) : from === 'calendrier' ? (<><Link href=\"/calendrier\" className=\"hover:text-primary\">Calendrier</Link><span className=\"material-symbols-outlined text-sm\">chevron_right</span><span className=\"text-on-surface font-semibold\">{nomComplet}</span></>) : from === 'dashboard' ? (<><Link href=\"/\" className=\"hover:text-primary\">Tableau de bord</Link><span className=\"material-symbols-outlined text-sm\">chevron_right</span><span className=\"text-on-surface font-semibold\">{nomComplet}</span></>) : (<><Link href=\"/patients\" className=\"hover:text-primary\">Patients</Link><span className=\"material-symbols-outlined text-sm\">chevron_right</span><span className=\"text-on-surface font-semibold\">{nomComplet}</span></>)}");
A("      </nav>");
A("");
A("      {valide && (");
A("        <div className=\"mb-6 flex items-center gap-3 bg-emerald-50 border border-emerald-200 rounded-xl px-5 py-4\">");
A("          <span className=\"material-symbols-outlined text-emerald-500 text-2xl\">check_circle</span>");
A("          <div>");
A("            <p className=\"font-bold text-emerald-700\">Dossier validé et transmis au rapport !</p>");
A("            <p className=\"text-xs text-emerald-600\">Redirection vers le rapport en cours...</p>");
A("          </div>");
A("        </div>");
A("      )}");
A("");
A("      {/* Header patient */}");
A("      <section className=\"bg-white rounded-xl shadow-sm border border-slate-200 p-6 flex items-start gap-8 mb-6\">");
A("        <div className=\"relative flex-shrink-0\">");
A("          <div className=\"w-32 h-32 rounded-xl bg-teal-100 flex items-center justify-center\">");
A("            <span className=\"text-4xl font-bold text-primary font-manrope\">{initials}</span>");
A("          </div>");
A("          <span className=\"absolute -bottom-2 -right-2 bg-teal-500 text-white p-1 rounded-full border-4 border-white\">");
A("            <span className=\"material-symbols-outlined text-sm\">check_circle</span>");
A("          </span>");
A("        </div>");
A("        <div className=\"flex-1\">");
A("          <div className=\"flex justify-between items-start\">");
A("            <div>");
A("              <h2 className=\"text-3xl font-bold text-primary font-manrope\">{nomComplet}</h2>");
A("              <p className=\"text-slate-500 font-medium mt-1\">ID: #{patient.numeroDossier || patient.id}</p>");
A("            </div>");
A("            <span className={'px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wide ' + (patient.statut==='actif'?'bg-emerald-50 text-emerald-700':patient.statut==='archive'?'bg-red-50 text-red-500':patient.statut==='en_attente'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-500')}>{patient.statut}</span>");
A("          </div>");
A("          <div className=\"grid grid-cols-2 lg:grid-cols-4 gap-4 mt-5 border-t border-slate-100 pt-5\">");
A("            {[");
A("              { label: 'Date de naissance', value: patient.dateNaissance || 'N/A' },");
A("              { label: 'Religion',          value: religion || '—' },");
A("              { label: 'Téléphone',         value: patient.telephone || 'N/A' },");
A("              { label: 'Dernière visite',   value: patient.dateDerniereVisite || 'N/A' },");
A("            ].map(item => (");
A("              <div key={item.label}>");
A("                <p className=\"text-xs font-semibold text-slate-400 uppercase tracking-widest\">{item.label}</p>");
A("                <p className=\"text-sm font-semibold text-on-surface mt-1\">{item.value}</p>");
A("              </div>");
A("            ))}");
A("          </div>");
A("        </div>");
A("      </section>");
A("");
A("      <div className=\"grid grid-cols-12 gap-6\">");
A("        <div className=\"col-span-12 lg:col-span-8 space-y-6\">");
A("");
A("          {/* 1 - SEANCE DU JOUR */}");
A("          <div className={'bg-white rounded-xl shadow-sm border p-6 ' + (valide ? 'border-emerald-200 bg-emerald-50/30' : 'border-slate-200')}>");
A("            <h3 className=\"font-headline-md text-on-surface flex items-center gap-2 mb-5\">");
A("              <span className=\"material-symbols-outlined text-primary\">today</span>");
A("              Séance du jour");
A("              {valide && <span className=\"ml-auto text-xs bg-emerald-50 text-emerald-600 px-2 py-0.5 rounded-full font-semibold flex items-center gap-1\"><span className=\"material-symbols-outlined text-sm\">lock</span>Validé</span>}");
A("            </h3>");
A("            <div className=\"grid grid-cols-2 gap-4 mb-4\">");
A("              <div>");
A("                <label className=\"text-xs font-bold text-slate-400 uppercase tracking-widest block mb-1\">Heure début</label>");
A("                <input type=\"time\" value={heureDebut} onChange={e => !valide && setHeureDebut(e.target.value)} disabled={valide}");
A("                  className={'w-full px-3 py-2 rounded-lg border text-sm outline-none ' + (valide ? 'bg-slate-100 border-slate-200 cursor-not-allowed' : 'bg-slate-50 border-slate-200 focus:border-primary focus:ring-1 focus:ring-primary')} />");
A("              </div>");
A("              <div>");
A("                <label className=\"text-xs font-bold text-slate-400 uppercase tracking-widest block mb-1\">Heure fin</label>");
A("                <input type=\"time\" value={heureFin} onChange={e => !valide && setHeureFin(e.target.value)} disabled={valide}");
A("                  className={'w-full px-3 py-2 rounded-lg border text-sm outline-none ' + (valide ? 'bg-slate-100 border-slate-200 cursor-not-allowed' : 'bg-slate-50 border-slate-200 focus:border-primary focus:ring-1 focus:ring-primary')} />");
A("              </div>");
A("            </div>");
A("            {!valide && (");
A("              <div>");
A("                <label className=\"text-xs font-bold text-slate-400 uppercase tracking-widest block mb-2\">Type de séance</label>");
A("                <div className=\"relative inline-block\">");
A("                  <button onClick={() => setShowTypeMenu(v => !v)}");
A("                    className={'flex items-center gap-2 px-4 py-2 rounded-xl border-2 font-semibold text-sm transition-all ' + (typeRdv ? TYPE_COLOR[typeRdv] : 'border-slate-200 text-slate-400 bg-slate-50')}>");
A("                    <span className=\"material-symbols-outlined text-sm\">category</span>");
A("                    {typeRdv ? typeRdv.charAt(0).toUpperCase() + typeRdv.slice(1) : 'Choisir un type'}");
A("                    <span className=\"material-symbols-outlined text-sm\">expand_more</span>");
A("                  </button>");
A("                  {showTypeMenu && (");
A("                    <div className=\"absolute top-full left-0 mt-1 bg-white rounded-xl shadow-xl border border-slate-200 z-20 overflow-hidden\">");
A("                      {TYPES.map(type => (");
A("                        <button key={type} onClick={() => { setTypeRdv(type); setShowTypeMenu(false) }}");
A("                          className={'w-full text-left px-5 py-2.5 text-sm font-semibold capitalize transition-colors hover:opacity-80 ' + TYPE_COLOR[type]}>");
A("                          {type}");
A("                        </button>");
A("                      ))}");
A("                    </div>");
A("                  )}");
A("                </div>");
A("              </div>");
A("            )}");
A("            {valide && typeRdv && (");
A("              <div>");
A("                <label className=\"text-xs font-bold text-slate-400 uppercase tracking-widest block mb-2\">Type de séance</label>");
A("                <span className={'text-sm font-bold px-4 py-2 rounded-xl border-2 inline-block capitalize ' + TYPE_COLOR[typeRdv]}>{typeRdv}</span>");
A("              </div>");
A("            )}");
A("          </div>");
A("");
A("          {/* 2 - ETAT CIVIL */}");
A("          <div className=\"bg-white rounded-xl shadow-sm border border-slate-200 p-6\">");
A("            <h3 className=\"font-headline-md text-on-surface flex items-center gap-2 mb-5\">");
A("              <span className=\"material-symbols-outlined text-primary\">badge</span>");
A("              État civil");
A("            </h3>");
A("            <ChampLibre label=\"Religion\" value={religion} onChange={setReligion} icon=\"church\" placeholder=\"Ex: Catholique, Protestant, Islam...\" rows={2} locked={valide} />");
A("          </div>");
A("");
A("          {/* 3 - MODE D ADMISSION */}");
A("          <div className=\"bg-white rounded-xl shadow-sm border border-slate-200 p-6\">");
A("            <h3 className=\"font-headline-md text-on-surface flex items-center gap-2 mb-5\">");
A("              <span className=\"material-symbols-outlined text-primary\">login</span>");
A("              Mode d'admission");
A("            </h3>");
A("            <div className=\"space-y-4\">");
A("              <ChampLibre label=\"Mode d'admission (service envoyeur)\" value={modeAdmission} onChange={setModeAdmission} icon=\"local_hospital\" placeholder=\"Ex: Service de chirurgie orthopédique...\" rows={2} locked={valide} />");
A("              <ChampLibre label=\"Auto référé\" value={autoRefere} onChange={setAutoRefere} icon=\"person_pin\" placeholder=\"Préciser si le patient s'est référé lui-même...\" rows={2} locked={valide} />");
A("              <ChampLibre label=\"Référé par\" value={referePar} onChange={setReferePar} icon=\"transfer_within_a_station\" placeholder=\"Nom du médecin ou service référent...\" rows={2} locked={valide} />");
A("            </div>");
A("          </div>");
A("");
A("          {/* 4 - OBJECTIF PRESEMPTEUR */}");
A("          <div className=\"bg-white rounded-xl shadow-sm border border-slate-200 p-6\">");
A("            <h3 className=\"font-headline-md text-on-surface flex items-center gap-2 mb-5\">");
A("              <span className=\"material-symbols-outlined text-primary\">flag</span>");
A("              Objectif présempteur");
A("            </h3>");
A("            <ChampLibre label=\"Objectif\" value={objectif} onChange={setObjectif} icon=\"target\" placeholder=\"Décrire l'objectif thérapeutique présempteur...\" rows={3} locked={valide} />");
A("          </div>");
A("");
A("          {/* 5 - BILAN KINESITHERAPIQUE */}");
A("          <div className=\"bg-white rounded-xl shadow-sm border border-slate-200 p-6\">");
A("            <h3 className=\"font-headline-md text-on-surface flex items-center gap-2 mb-5\">");
A("              <span className=\"material-symbols-outlined text-primary\">fact_check</span>");
A("              Bilan kinésithérapique");
A("            </h3>");
A("            <div className=\"space-y-4\">");
A("              <ChampLibre label=\"Antécédents\" value={antecedents} onChange={setAntecedents} icon=\"history\" placeholder=\"Antécédents médicaux, chirurgicaux, familiaux...\" rows={3} locked={valide} />");
A("              <ChampLibre label=\"Histoire de la maladie\" value={historieMaladie} onChange={setHistorieMaladie} icon=\"timeline\" placeholder=\"Décrire l'évolution de la maladie depuis le début...\" rows={3} locked={valide} />");
A("              <ChampLibre label=\"Bilan fonctionnel\" value={bilanFonctionnel} onChange={setBilanFonctionnel} icon=\"accessibility_new\" placeholder=\"Évaluation des capacités fonctionnelles du patient...\" rows={3} locked={valide} />");
A("              <ChampLibre label=\"Bilan d'incapacité\" value={bilanIncapacite} onChange={setBilanIncapacite} icon=\"personal_injury\" placeholder=\"Évaluation des incapacités et limitations...\" rows={3} locked={valide} />");
A("            </div>");
A("          </div>");
A("");
A("          {/* 6 - DIAGNOSTIC KINE */}");
A("          <div className=\"bg-white rounded-xl shadow-sm border border-slate-200 p-6\">");
A("            <h3 className=\"font-headline-md text-on-surface flex items-center gap-2 mb-5\">");
A("              <span className=\"material-symbols-outlined text-primary\">diagnosis</span>");
A("              Diagnostic kinésithérapique");
A("            </h3>");
A("            <ChampLibre label=\"Diagnostic kinésithérapique\" value={diagnosticKine} onChange={setDiagnosticKine} icon=\"medical_information\" placeholder=\"Diagnostic établi par le kinésithérapeute...\" rows={3} locked={valide} />");
A("          </div>");
A("");
A("          {/* 7 - TRAITEMENT */}");
A("          <SectionHistorique label=\"Traitement\" icon=\"vaccines\"");
A("            value={traitement} onChange={setTraitement}");
A("            historique={historiqueTraitement}");
A("            onEnregistrer={() => enregistrer(traitement, setTraitement, setHistoriqueTraitement)}");
A("            colorClass=\"bg-blue-50 border-blue-100\" timeClass=\"text-blue-400\" locked={valide} />");
A("");
A("          {/* 8 - EVOLUTION ET SUIVI */}");
A("          <SectionHistorique label=\"Évolution et suivi\" icon=\"trending_up\"");
A("            value={evolution} onChange={setEvolution}");
A("            historique={historiqueEvolution}");
A("            onEnregistrer={() => enregistrer(evolution, setEvolution, setHistoriqueEvolution)}");
A("            colorClass=\"bg-emerald-50 border-emerald-100\" timeClass=\"text-emerald-500\" locked={valide} />");
A("");
A("          {/* 9 - CONSEIL */}");
A("          <div className=\"bg-white rounded-xl shadow-sm border border-slate-200 p-6\">");
A("            <h3 className=\"font-headline-md text-on-surface flex items-center gap-2 mb-4\">");
A("              <span className=\"material-symbols-outlined text-primary\">lightbulb</span>");
A("              Conseil");
A("              {valide && <span className=\"ml-auto text-xs bg-emerald-50 text-emerald-600 px-2 py-0.5 rounded-full font-semibold flex items-center gap-1\"><span className=\"material-symbols-outlined text-sm\">lock</span>Validé</span>}");
A("            </h3>");
A("            <ChampLibre label=\"Conseils au patient\" value={conseil} onChange={setConseil} icon=\"tips_and_updates\" placeholder=\"Conseils hygiéno-diététiques, posturaux, exercices à domicile...\" rows={4} locked={valide} />");
A("          </div>");
A("");
A("          {/* BOUTON VALIDER */}");
A("          {!valide && (");
A("            <div className=\"bg-white rounded-xl shadow-sm border border-slate-200 p-6 flex flex-col items-center gap-3\">");
A("              <p className=\"text-sm text-on-surface-variant text-center\">Une fois validé, le dossier sera transmis au rapport et ne pourra plus être modifié.</p>");
A("              <button onClick={() => setShowConfirm(true)}");
A("                className=\"flex items-center gap-2 px-8 py-3 rounded-xl bg-emerald-500 text-white font-bold text-base shadow-lg hover:bg-emerald-600 transition-all\">");
A("                <span className=\"material-symbols-outlined\">check_circle</span>");
A("                Valider le dossier");
A("              </button>");
A("            </div>");
A("          )}");
A("");
A("        </div>");
A("");
A("        {/* COLONNE DROITE */}");
A("        <div className=\"col-span-12 lg:col-span-4 space-y-6\">");
A("          <div className=\"bg-white rounded-xl shadow-sm border border-slate-200 p-6\">");
A("            <h4 className=\"font-title-sm text-on-surface mb-4\">Actions rapides</h4>");
A("            <div className=\"space-y-3\">");
A("              <button className=\"w-full flex items-center gap-3 px-4 py-3 rounded-lg bg-primary text-white font-semibold text-sm hover:opacity-90 transition-all\">");
A("                <span className=\"material-symbols-outlined text-lg\">event_available</span>");
A("                Nouveau rendez-vous");
A("              </button>");
A("              <button className=\"w-full flex items-center gap-3 px-4 py-3 rounded-lg border border-slate-200 text-on-surface font-semibold text-sm hover:bg-slate-50 transition-all\">");
A("                <span className=\"material-symbols-outlined text-lg\">edit</span>");
A("                Modifier le profil");
A("              </button>");
A("              {from === 'archives' ? (");
A("                <Link href=\"/archives\" className=\"w-full flex items-center gap-3 px-4 py-3 rounded-lg border border-slate-200 text-on-surface font-semibold text-sm hover:bg-slate-50 transition-all\">");
A("                  <span className=\"material-symbols-outlined text-lg\">arrow_back</span>Retour aux archives");
A("                </Link>");
A("              ) : from === 'calendrier' ? (");
A("                <Link href=\"/calendrier\" className=\"w-full flex items-center gap-3 px-4 py-3 rounded-lg border border-slate-200 text-on-surface font-semibold text-sm hover:bg-slate-50 transition-all\">");
A("                  <span className=\"material-symbols-outlined text-lg\">arrow_back</span>Retour au calendrier");
A("                </Link>");
A("              ) : from === 'dashboard' ? (");
A("                <Link href=\"/\" className=\"w-full flex items-center gap-3 px-4 py-3 rounded-lg border border-slate-200 text-on-surface font-semibold text-sm hover:bg-slate-50 transition-all\">");
A("                  <span className=\"material-symbols-outlined text-lg\">arrow_back</span>Retour au tableau de bord");
A("                </Link>");
A("              ) : (");
A("                <Link href=\"/patients\" className=\"w-full flex items-center gap-3 px-4 py-3 rounded-lg border border-slate-200 text-on-surface font-semibold text-sm hover:bg-slate-50 transition-all\">");
A("                  <span className=\"material-symbols-outlined text-lg\">arrow_back</span>Retour a la liste");
A("                </Link>");
A("              )}");
A("            </div>");
A("          </div>");
A("");
A("          <div className=\"bg-primary rounded-xl shadow-lg p-6 text-white relative overflow-hidden\">");
A("            <div className=\"relative z-10\">");
A("              <h4 className=\"font-bold text-lg mb-2\">Dossier Patient</h4>");
A("              <p className=\"text-teal-200 text-sm mb-1\">N° {patient.numeroDossier || patient.id}</p>");
A("              <p className=\"text-teal-200 text-sm mb-4\">Admission : {patient.dateAdmission || 'N/A'}</p>");
A("              <div className={'inline-block px-3 py-1 rounded-full text-xs font-bold uppercase ' + (patient.statut==='actif'?'bg-emerald-400 text-white':patient.statut==='archive'?'bg-red-400 text-white':'bg-amber-400 text-white')}>");
A("                {patient.statut}");
A("              </div>");
A("            </div>");
A("            <span className=\"material-symbols-outlined absolute -right-4 -bottom-4 text-8xl text-white/10 rotate-12\">folder_shared</span>");
A("          </div>");
A("        </div>");
A("      </div>");
A("");
A("      {/* MODAL CONFIRMATION VALIDATION */}");
A("      {showConfirm && (");
A("        <div className=\"fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm\">");
A("          <div className=\"bg-surface rounded-2xl shadow-2xl p-8 max-w-sm w-full mx-4 text-center\">");
A("            <div className=\"w-16 h-16 bg-emerald-50 rounded-full flex items-center justify-center mx-auto mb-4\">");
A("              <span className=\"material-symbols-outlined text-emerald-500 text-3xl\">check_circle</span>");
A("            </div>");
A("            <h3 className=\"text-lg font-bold text-on-surface mb-2\">Confirmer la validation</h3>");
A("            <p className=\"text-sm text-on-surface-variant mb-6\">Une fois validé, le dossier sera <strong>verrouillé</strong> et transmis automatiquement au rapport. Cette action est <strong>irréversible</strong>.</p>");
A("            <div className=\"flex gap-3\">");
A("              <button onClick={() => setShowConfirm(false)}");
A("                className=\"flex-1 px-4 py-2.5 rounded-lg border border-outline-variant text-on-surface font-semibold text-sm hover:bg-surface-container-low\">");
A("                Annuler");
A("              </button>");
A("              <button onClick={confirmerValidation}");
A("                className=\"flex-1 px-4 py-2.5 rounded-lg bg-emerald-500 text-white font-semibold text-sm hover:bg-emerald-600 shadow-sm\">");
A("                Confirmer");
A("              </button>");
A("            </div>");
A("          </div>");
A("        </div>");
A("      )}");
A("");
A("    </AppShell>");
A("  )");
A("}");

fs.writeFileSync('D:/chu_kine/projet_frontend/src/app/patients/[id]/page.tsx', lines.join('\n'), {encoding:'utf8'});
console.log('patients/[id]/page.tsx - version finale avec validation !');
