const fs = require('fs');
const lines = [];
const A = (s) => lines.push(s);

A("'use client'");
A("");
A("import { useState, useEffect, useMemo } from 'react'");
A("import AppShell from '@/components/layout/AppShell'");
A("import { useLanguage } from '@/context/LanguageContext'");
A("");
A("const API = process.env.NEXT_PUBLIC_API_URL");
A("");
A("interface Patient {");
A("  id: number; nom: string; prenom: string; diagnostic?: string;");
A("  numeroDossier?: string; statut?: string;");
A("}");
A("");
A("interface RendezVous {");
A("  id: number; date: string; heureDebut: string; heureFin: string;");
A("  motif: string; type: string; statut: string; notes?: string;");
A("  patient?: Patient; patientId: number;");
A("}");
A("");
A("type Periode = 'jour' | 'semaine' | 'mois' | 'annee'");
A("");
A("function toKey(d: Date) {");
A("  return d.getFullYear() + '-' + String(d.getMonth()+1).padStart(2,'0') + '-' + String(d.getDate()).padStart(2,'0')");
A("}");
A("");
A("function startOfWeek(d: Date) {");
A("  const r = new Date(d); const day = r.getDay(); const diff = day===0?-6:1-day;");
A("  r.setDate(r.getDate()+diff); r.setHours(0,0,0,0); return r;");
A("}");
A("");
A("export default function RapportPage() {");
A("  const { t } = useLanguage()");
A("  const [rdvs, setRdvs]         = useState<RendezVous[]>([])");
A("  const [patients, setPatients] = useState<Patient[]>([])");
A("  const [loading, setLoading]   = useState(true)");
A("  const [periode, setPeriode]   = useState<Periode>('mois')");
A("  const [refDate, setRefDate]   = useState(new Date())");
A("");
A("  useEffect(() => {");
A("    Promise.all([");
A("      fetch(API + '/rendezvous').then(r => r.json()),");
A("      fetch(API + '/patients').then(r => r.json()),");
A("    ]).then(([r, p]) => {");
A("      if (Array.isArray(r)) setRdvs(r)");
A("      if (Array.isArray(p)) setPatients(p)");
A("    }).catch(() => {}).finally(() => setLoading(false))");
A("  }, [])");
A("");
A("  const { debut, fin, label } = useMemo(() => {");
A("    const d = new Date(refDate); d.setHours(0,0,0,0);");
A("    if (periode === 'jour') {");
A("      return { debut: toKey(d), fin: toKey(d), label: d.toLocaleDateString('fr-FR', { weekday:'long', day:'numeric', month:'long', year:'numeric' }) }");
A("    }");
A("    if (periode === 'semaine') {");
A("      const s = startOfWeek(d);");
A("      const e = new Date(s); e.setDate(e.getDate()+6);");
A("      return { debut: toKey(s), fin: toKey(e), label: s.toLocaleDateString('fr-FR',{day:'numeric',month:'short'}) + ' – ' + e.toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'}) }");
A("    }");
A("    if (periode === 'mois') {");
A("      const s = new Date(d.getFullYear(), d.getMonth(), 1);");
A("      const e = new Date(d.getFullYear(), d.getMonth()+1, 0);");
A("      return { debut: toKey(s), fin: toKey(e), label: d.toLocaleDateString('fr-FR',{month:'long',year:'numeric'}) }");
A("    }");
A("    const s = new Date(d.getFullYear(), 0, 1);");
A("    const e = new Date(d.getFullYear(), 11, 31);");
A("    return { debut: toKey(s), fin: toKey(e), label: String(d.getFullYear()) }");
A("  }, [periode, refDate])");
A("");
A("  const filtered = useMemo(() =>");
A("    rdvs.filter(r => r.date >= debut && r.date <= fin)");
A("  , [rdvs, debut, fin])");
A("");
A("  const stats = useMemo(() => {");
A("    const total       = filtered.length");
A("    const effectues   = filtered.filter(r => r.statut === 'effectue' || r.statut === 'termine').length");
A("    const planifies   = filtered.filter(r => r.statut === 'planifie').length");
A("    const annules     = filtered.filter(r => r.statut === 'annule').length");
A("    const patientsIds = [...new Set(filtered.map(r => r.patientId))]");
A("    const nbPatients  = patientsIds.length");
A("    const byType: Record<string,number> = {}");
A("    filtered.forEach(r => { byType[r.type||'autre'] = (byType[r.type||'autre']||0)+1 })");
A("    return { total, effectues, planifies, annules, nbPatients, byType }");
A("  }, [filtered])");
A("");
A("  function navigate(dir: number) {");
A("    const d = new Date(refDate)");
A("    if (periode==='jour')    d.setDate(d.getDate()+dir)");
A("    if (periode==='semaine') d.setDate(d.getDate()+dir*7)");
A("    if (periode==='mois')    d.setMonth(d.getMonth()+dir)");
A("    if (periode==='annee')   d.setFullYear(d.getFullYear()+dir)");
A("    setRefDate(d)");
A("  }");
A("");
A("  const TYPE_COLOR: Record<string,string> = {");
A("    consultation: 'bg-teal-100 text-teal-700 border-teal-300',");
A("    soin:         'bg-blue-100 text-blue-700 border-blue-300',");
A("    bilan:        'bg-purple-100 text-purple-700 border-purple-300',");
A("    exercice:     'bg-amber-100 text-amber-700 border-amber-300',");
A("    autre:        'bg-slate-100 text-slate-600 border-slate-300',");
A("  }");
A("");
A("  const STATUT_STYLE: Record<string,string> = {");
A("    effectue:  'bg-emerald-100 text-emerald-700',");
A("    termine:   'bg-emerald-100 text-emerald-700',");
A("    planifie:  'bg-amber-100 text-amber-700',");
A("    annule:    'bg-red-100 text-red-500',");
A("  }");
A("");
A("  return (");
A("    <AppShell searchPlaceholder=\"Rechercher...\" showSearch={false}>");
A("");
A("      {/* EN-TETE */}");
A("      <div className=\"flex flex-col sm:flex-row sm:justify-between sm:items-start gap-4 mb-6 print:mb-4\">");
A("        <div>");
A("          <div className=\"flex items-center gap-3 mb-1\">");
A("            <span className=\"material-symbols-outlined text-primary text-2xl\">assessment</span>");
A("            <h2 className=\"text-2xl font-bold text-on-surface font-manrope\">Rapport d'activité</h2>");
A("          </div>");
A("          <p className=\"text-sm text-on-surface-variant\">Consultation uniquement — lecture seule</p>");
A("        </div>");
A("        <button onClick={() => window.print()}");
A("          className=\"flex items-center gap-2 px-5 py-2.5 rounded-xl bg-primary text-white font-semibold text-sm shadow hover:opacity-90 transition print:hidden\">");
A("          <span className=\"material-symbols-outlined text-sm\">print</span>");
A("          Imprimer / PDF");
A("        </button>");
A("      </div>");
A("");
A("      {/* FILTRES PERIODE */}");
A("      <div className=\"flex flex-wrap items-center gap-3 mb-6 print:hidden\">");
A("        <div className=\"flex rounded-xl border border-outline-variant overflow-hidden text-sm\">");
A("          {(['jour','semaine','mois','annee'] as Periode[]).map(p => (");
A("            <button key={p} onClick={() => setPeriode(p)}");
A("              className={'px-4 py-2 font-semibold transition-colors capitalize ' + (periode===p?'bg-primary text-white':'text-on-surface-variant hover:bg-surface-container-low')}>");
A("              {p==='jour'?'Jour':p==='semaine'?'Semaine':p==='mois'?'Mois':'Année'}");
A("            </button>");
A("          ))}");
A("        </div>");
A("        <div className=\"flex items-center gap-2\">");
A("          <button onClick={() => navigate(-1)} className=\"w-9 h-9 rounded-lg border border-outline-variant flex items-center justify-center hover:bg-surface-container-low transition\">");
A("            <span className=\"material-symbols-outlined text-sm\">chevron_left</span>");
A("          </button>");
A("          <span className=\"text-sm font-semibold text-on-surface px-2 capitalize\">{label}</span>");
A("          <button onClick={() => navigate(1)} className=\"w-9 h-9 rounded-lg border border-outline-variant flex items-center justify-center hover:bg-surface-container-low transition\">");
A("            <span className=\"material-symbols-outlined text-sm\">chevron_right</span>");
A("          </button>");
A("          <button onClick={() => setRefDate(new Date())} className=\"px-3 py-1.5 rounded-lg border border-outline-variant text-xs font-semibold text-on-surface-variant hover:bg-surface-container-low transition\">");
A("            Aujourd'hui");
A("          </button>");
A("        </div>");
A("      </div>");
A("");
A("      {/* TITRE PERIODE (impression) */}");
A("      <div className=\"hidden print:block mb-4\">");
A("        <p className=\"text-sm text-on-surface-variant\">Période : <strong className=\"capitalize\">{label}</strong></p>");
A("        <p className=\"text-xs text-on-surface-variant\">Généré le {new Date().toLocaleDateString('fr-FR', { day:'numeric', month:'long', year:'numeric', hour:'2-digit', minute:'2-digit' })}</p>");
A("      </div>");
A("");
A("      {loading ? (");
A("        <div className=\"flex flex-col items-center justify-center py-24 text-on-surface-variant\">");
A("          <div className=\"w-10 h-10 border-4 border-primary border-t-transparent rounded-full animate-spin mb-4\"></div>");
A("          <p className=\"text-sm\">Chargement du rapport...</p>");
A("        </div>");
A("      ) : (");
A("        <div className=\"space-y-6\">");
A("");
A("          {/* CARTES STATISTIQUES */}");
A("          <div className=\"grid grid-cols-2 lg:grid-cols-4 gap-4\">");
A("            {[");
A("              { icon: 'event_note',    label: 'Total RDV',        value: stats.total,      color: 'text-primary',      bg: 'bg-teal-50' },");
A("              { icon: 'check_circle',  label: 'Effectués',        value: stats.effectues,  color: 'text-emerald-600',  bg: 'bg-emerald-50' },");
A("              { icon: 'schedule',      label: 'Planifiés',        value: stats.planifies,  color: 'text-amber-600',    bg: 'bg-amber-50' },");
A("              { icon: 'person',        label: 'Patients traités', value: stats.nbPatients, color: 'text-blue-600',     bg: 'bg-blue-50' },");
A("            ].map(s => (");
A("              <div key={s.label} className={'rounded-xl border border-outline-variant p-5 flex flex-col gap-2 ' + s.bg}>");
A("                <div className=\"flex items-center gap-2\">");
A("                  <span className={'material-symbols-outlined text-lg ' + s.color}>{s.icon}</span>");
A("                  <span className=\"text-xs font-semibold text-on-surface-variant uppercase tracking-wider\">{s.label}</span>");
A("                </div>");
A("                <p className={'text-3xl font-bold ' + s.color}>{s.value}</p>");
A("              </div>");
A("            ))}");
A("          </div>");
A("");
A("          {/* REPARTITION PAR TYPE */}");
A("          {Object.keys(stats.byType).length > 0 && (");
A("            <div className=\"bg-surface rounded-xl border border-outline-variant p-5\">");
A("              <div className=\"flex items-center gap-2 mb-4\">");
A("                <span className=\"material-symbols-outlined text-primary\">donut_small</span>");
A("                <h3 className=\"font-semibold text-on-surface\">Répartition par type</h3>");
A("              </div>");
A("              <div className=\"flex flex-wrap gap-3\">");
A("                {Object.entries(stats.byType).map(([type, nb]) => (");
A("                  <div key={type} className={'flex items-center gap-2 px-4 py-2 rounded-xl border text-sm font-semibold ' + (TYPE_COLOR[type]||TYPE_COLOR.autre)}>");
A("                    <span className=\"capitalize\">{type}</span>");
A("                    <span className=\"bg-white/60 rounded-full px-2 py-0.5 text-xs font-bold\">{nb}</span>");
A("                  </div>");
A("                ))}");
A("              </div>");
A("            </div>");
A("          )}");
A("");
A("          {/* TABLEAU DETAIL */}");
A("          <div className=\"bg-surface rounded-xl border border-outline-variant overflow-hidden\">");
A("            <div className=\"px-6 py-4 border-b border-outline-variant bg-surface-container-low/50 flex items-center justify-between\">");
A("              <div className=\"flex items-center gap-2\">");
A("                <span className=\"material-symbols-outlined text-primary\">table_view</span>");
A("                <h3 className=\"font-semibold text-on-surface\">Détail des rendez-vous</h3>");
A("              </div>");
A("              <span className=\"text-xs text-on-surface-variant bg-surface-container-low px-3 py-1 rounded-full\">{filtered.length} entrée{filtered.length>1?'s':''}</span>");
A("            </div>");
A("");
A("            {filtered.length === 0 ? (");
A("              <div className=\"flex flex-col items-center justify-center py-16 text-on-surface-variant\">");
A("                <span className=\"material-symbols-outlined text-4xl mb-3\">event_busy</span>");
A("                <p className=\"text-sm\">Aucun rendez-vous sur cette période</p>");
A("              </div>");
A("            ) : (");
A("              <div className=\"overflow-x-auto\">");
A("                <table className=\"w-full text-sm\">");
A("                  <thead className=\"bg-surface-container-low/80\">");
A("                    <tr>");
A("                      <th className=\"text-left px-4 py-3 text-xs font-bold text-on-surface-variant uppercase tracking-wider\">Date</th>");
A("                      <th className=\"text-left px-4 py-3 text-xs font-bold text-on-surface-variant uppercase tracking-wider\">Heure</th>");
A("                      <th className=\"text-left px-4 py-3 text-xs font-bold text-on-surface-variant uppercase tracking-wider\">Patient</th>");
A("                      <th className=\"text-left px-4 py-3 text-xs font-bold text-on-surface-variant uppercase tracking-wider\">Motif</th>");
A("                      <th className=\"text-left px-4 py-3 text-xs font-bold text-on-surface-variant uppercase tracking-wider\">Type</th>");
A("                      <th className=\"text-left px-4 py-3 text-xs font-bold text-on-surface-variant uppercase tracking-wider\">Statut</th>");
A("                    </tr>");
A("                  </thead>");
A("                  <tbody className=\"divide-y divide-outline-variant\">");
A("                    {filtered.sort((a,b) => a.date.localeCompare(b.date) || a.heureDebut.localeCompare(b.heureDebut)).map(r => (");
A("                      <tr key={r.id} className=\"hover:bg-surface-container-low/30 transition-colors\">");
A("                        <td className=\"px-4 py-3 text-on-surface-variant\">");
A("                          {new Date(r.date + 'T00:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'})}");
A("                        </td>");
A("                        <td className=\"px-4 py-3 font-mono text-xs text-on-surface\">");
A("                          {r.heureDebut?.substring(0,5)} – {r.heureFin?.substring(0,5)}");
A("                        </td>");
A("                        <td className=\"px-4 py-3\">");
A("                          {r.patient ? (");
A("                            <div>");
A("                              <p className=\"font-semibold text-on-surface\">{r.patient.prenom} {r.patient.nom}</p>");
A("                              <p className=\"text-[10px] text-on-surface-variant\">{r.patient.numeroDossier||'ID #'+r.patientId}</p>");
A("                            </div>");
A("                          ) : <span className=\"text-on-surface-variant\">—</span>}");
A("                        </td>");
A("                        <td className=\"px-4 py-3 text-on-surface max-w-[180px] truncate\">{r.motif||'—'}</td>");
A("                        <td className=\"px-4 py-3\">");
A("                          <span className={'text-[11px] font-bold px-2.5 py-1 rounded-lg border capitalize ' + (TYPE_COLOR[r.type||'autre']||TYPE_COLOR.autre)}>");
A("                            {r.type||'—'}");
A("                          </span>");
A("                        </td>");
A("                        <td className=\"px-4 py-3\">");
A("                          <span className={'text-[11px] font-bold px-2.5 py-1 rounded-full capitalize ' + (STATUT_STYLE[r.statut]||'bg-slate-100 text-slate-500')}>");
A("                            {r.statut}");
A("                          </span>");
A("                        </td>");
A("                      </tr>");
A("                    ))}");
A("                  </tbody>");
A("                </table>");
A("              </div>");
A("            )}");
A("          </div>");
A("");
A("        </div>");
A("      )}");
A("    </AppShell>");
A("  )");
A("}");

fs.writeFileSync('D:/chu_kine/projet_frontend/src/app/rapport/page.tsx', lines.join('\n'), {encoding:'utf8'});
console.log('rapport/page.tsx cree avec succes !');
