const fs = require('fs');
const lines = [];
const A = (s) => lines.push(s);

A("'use client'");
A("");
A("import { useState, useEffect, useMemo } from 'react'");
A("import Link from 'next/link'");
A("import AppShell from '@/components/layout/AppShell'");
A("import { useLanguage } from '@/context/LanguageContext'");
A("");
A("const API = process.env.NEXT_PUBLIC_API_URL");
A("");
A("interface Patient {");
A("  id: number");
A("  numeroDossier: string");
A("  nom: string");
A("  prenom: string");
A("  dateNaissance: string");
A("  sexe: string");
A("  diagnostic: string");
A("  statut: string");
A("  dateAdmission: string");
A("  dateDerniereVisite: string");
A("}");
A("");
A("const statutStyle: Record<string, string> = {");
A("  actif: 'bg-emerald-50 text-emerald-700',");
A("  inactif: 'bg-surface-container-low text-on-surface-variant',");
A("  en_attente: 'bg-amber-50 text-amber-700',");
A("  archive: 'bg-red-50 text-red-500',");
A("}");
A("");
A("export default function PatientsPage() {");
A("  const { t } = useLanguage()");
A("  const [patients, setPatients] = useState<Patient[]>([])");
A("  const [loading, setLoading] = useState(true)");
A("  const [search, setSearch] = useState('')");
A("  const [filterStatut, setFilterStatut] = useState('tous')");
A("  const [confirmId, setConfirmId] = useState<number | null>(null)");
A("");
A("  const statutLabel: Record<string, string> = {");
A("    actif: t('pat_actif'),");
A("    inactif: t('pat_inactif'),");
A("    en_attente: t('pat_enAttente'),");
A("    archive: t('pat_archive'),");
A("  }");
A("");
A("  useEffect(() => {");
A("    fetch(API + '/patients')");
A("      .then((r) => r.json())");
A("      .then((data) => {");
A("        if (Array.isArray(data)) setPatients(data)");
A("      })");
A("      .catch(() => {})");
A("      .finally(() => setLoading(false))");
A("  }, [])");
A("");
A("  const filtered = useMemo(() => {");
A("    let list = patients");
A("    const s = search.trim().replace(/\\s+/g, ' ').toLowerCase()");
A("    if (s) {");
A("      list = list.filter((p) => {");
A("        const nomComplet = (p.prenom + ' ' + p.nom).toLowerCase()");
A("        const nomInverse = (p.nom + ' ' + p.prenom).toLowerCase()");
A("        return (");
A("          nomComplet.includes(s) ||");
A("          nomInverse.includes(s) ||");
A("          p.nom?.toLowerCase().includes(s) ||");
A("          p.prenom?.toLowerCase().includes(s) ||");
A("          p.numeroDossier?.toLowerCase().includes(s) ||");
A("          p.diagnostic?.toLowerCase().includes(s)");
A("        )");
A("      })");
A("    }");
A("    if (filterStatut !== 'tous') list = list.filter((p) => p.statut === filterStatut)");
A("    return list");
A("  }, [search, filterStatut, patients])");
A("");
A("  async function archiver(id: number) {");
A("    try {");
A("      await fetch(API + '/patients/' + id + '/archiver', { method: 'PATCH' })");
A("    } catch {}");
A("    setPatients((prev) => prev.map((p) => p.id === id ? { ...p, statut: 'archive' } : p))");
A("    setConfirmId(null)");
A("  }");
A("");
A("  return (");
A("    <AppShell searchPlaceholder={t('pat_rechercherPlaceholder')} showSearch={false}>");
A("      <div className=\"flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4 mb-6\">");
A("        <div>");
A("          <h2 className=\"text-2xl font-bold text-on-surface font-manrope\">{t('pat_titre')}</h2>");
A("          <p className=\"text-sm text-on-surface-variant mt-1\">{patients.length} {t('pat_enregistres')}</p>");
A("        </div>");
A("        <Link href=\"/patients/nouveau\" className=\"btn-primary\">");
A("          <span className=\"material-symbols-outlined text-lg\">person_add</span>");
A("          {t('pat_nouveauPatient')}");
A("        </Link>");
A("      </div>");
A("");
A("      <div className=\"flex flex-col sm:flex-row gap-3 mb-6\">");
A("        <div className=\"flex items-center gap-3 bg-surface border border-outline-variant px-4 py-2 rounded-lg flex-1 max-w-md\">");
A("          <span className=\"material-symbols-outlined text-on-surface-variant text-lg\">search</span>");
A("          <input");
A("            type=\"text\"");
A("            placeholder={t('pat_rechercherPlaceholder')}");
A("            value={search}");
A("            onChange={(e) => setSearch(e.target.value)}");
A("            className=\"bg-transparent border-none focus:outline-none text-sm w-full text-on-surface placeholder:text-on-surface-variant\"");
A("          />");
A("          {search && (");
A("            <button");
A("              onClick={() => setSearch('')}");
A("              className=\"text-on-surface-variant hover:text-red-500 transition-colors flex-shrink-0\"");
A("            >");
A("              <span className=\"material-symbols-outlined text-lg\">close</span>");
A("            </button>");
A("          )}");
A("        </div>");
A("        <select");
A("          value={filterStatut}");
A("          onChange={(e) => setFilterStatut(e.target.value)}");
A("          className=\"px-4 py-2 rounded-lg border border-outline-variant bg-surface text-sm text-on-surface focus:outline-none\"");
A("        >");
A("          <option value=\"tous\">{t('pat_tousLesStatuts')}</option>");
A("          <option value=\"actif\">{t('pat_actif')}</option>");
A("          <option value=\"inactif\">{t('pat_inactif')}</option>");
A("          <option value=\"en_attente\">{t('pat_enAttente')}</option>");
A("          <option value=\"archive\">{t('pat_archive')}</option>");
A("        </select>");
A("        {(search || filterStatut !== 'tous') && (");
A("          <button");
A("            onClick={() => { setSearch(''); setFilterStatut('tous') }}");
A("            className=\"px-4 py-2 rounded-lg border border-outline-variant bg-surface text-sm text-red-500 font-semibold hover:bg-red-50 transition-colors flex items-center gap-2\"");
A("          >");
A("            <span className=\"material-symbols-outlined text-lg\">filter_alt_off</span>");
A("            {t('pat_toutAfficher')}");
A("          </button>");
A("        )}");
A("      </div>");
A("");
A("      {loading ? (");
A("        <div className=\"flex flex-col items-center justify-center py-24 text-on-surface-variant\">");
A("          <div className=\"w-10 h-10 border-4 border-primary border-t-transparent rounded-full animate-spin mb-4\"></div>");
A("          <p className=\"text-sm\">{t('pat_chargement')}</p>");
A("        </div>");
A("      ) : (");
A("        <div className=\"bg-surface rounded-xl border border-outline-variant shadow-sm overflow-hidden\">");
A("          <div className=\"overflow-x-auto\">");
A("            <table className=\"w-full\">");
A("              <thead>");
A("                <tr className=\"border-b border-outline-variant bg-surface-container-low/50\">");
A("                  <th className=\"table-header\">{t('pat_colDossier')}</th>");
A("                  <th className=\"table-header\">{t('pat_colPatient')}</th>");
A("                  <th className=\"table-header\">{t('pat_colDiagnostic')}</th>");
A("                  <th className=\"table-header\">{t('pat_colStatut')}</th>");
A("                  <th className=\"table-header\">{t('pat_colDerniereVisite')}</th>");
A("                  <th className=\"table-header text-center\">{t('pat_colArchive')}</th>");
A("                  <th className=\"table-header w-10\"></th>");
A("                </tr>");
A("              </thead>");
A("              <tbody>");
A("                {filtered.map((p) => (");
A("                  <tr key={p.id} className=\"hover:bg-surface-container-low/50 transition-colors\">");
A("                    <td className=\"table-cell\">");
A("                      <span className=\"text-xs font-mono text-primary font-semibold\">{p.numeroDossier || '-'}</span>");
A("                    </td>");
A("                    <td className=\"table-cell\">");
A("                      <Link href={'/patients/' + p.id} className=\"hover:underline\">");
A("                        <p className=\"font-semibold text-on-surface\">{p.prenom} {p.nom}</p>");
A("                        <p className=\"text-xs text-on-surface-variant\">{p.dateNaissance} - {p.sexe === 'M' ? t('cal_homme') : t('cal_femme')}</p>");
A("                      </Link>");
A("                    </td>");
A("                    <td className=\"table-cell\">");
A("                      <p className=\"text-sm text-on-surface max-w-[200px] truncate\">{p.diagnostic || '-'}</p>");
A("                    </td>");
A("                    <td className=\"table-cell\">");
A("                      <span className={'px-3 py-1 rounded-full text-xs font-bold ' + (statutStyle[p.statut] || 'bg-surface-container-low text-on-surface-variant')}>");
A("                        {statutLabel[p.statut] || p.statut}");
A("                      </span>");
A("                    </td>");
A("                    <td className=\"table-cell text-xs text-on-surface-variant\">");
A("                      {p.dateDerniereVisite || '-'}");
A("                    </td>");
A("                    <td className=\"table-cell text-center\">");
A("                      {p.statut !== 'archive' ? (");
A("                        <button");
A("                          onClick={() => setConfirmId(p.id)}");
A("                          className=\"inline-flex items-center gap-1 px-3 py-1.5 rounded-lg bg-amber-50 text-amber-700 text-xs font-semibold hover:bg-amber-100 transition-colors border border-amber-200\"");
A("                        >");
A("                          <span className=\"material-symbols-outlined text-sm\">inventory_2</span>");
A("                          {t('pat_btnArchiver')}");
A("                        </button>");
A("                      ) : (");
A("                        <span className=\"inline-flex items-center gap-1 px-3 py-1.5 rounded-lg bg-surface-container-low text-on-surface-variant text-xs font-semibold\">");
A("                          <span className=\"material-symbols-outlined text-sm\">check_circle</span>");
A("                          {t('pat_archive')}");
A("                        </span>");
A("                      )}");
A("                    </td>");
A("                    <td className=\"table-cell\">");
A("                      <Link href={'/patients/' + p.id} className=\"material-symbols-outlined text-on-surface-variant hover:text-primary transition-colors text-lg\">");
A("                        chevron_right");
A("                      </Link>");
A("                    </td>");
A("                  </tr>");
A("                ))}");
A("              </tbody>");
A("            </table>");
A("            {filtered.length === 0 && (");
A("              <div className=\"py-12 text-center text-on-surface-variant\">");
A("                <span className=\"material-symbols-outlined text-4xl mb-2\">search_off</span>");
A("                <p className=\"mb-4\">{t('pat_aucunTrouve')}</p>");
A("                <button");
A("                  onClick={() => { setSearch(''); setFilterStatut('tous') }}");
A("                  className=\"px-4 py-2 rounded-lg bg-primary text-white text-sm font-semibold hover:opacity-90\"");
A("                >");
A("                  {t('pat_voirTousPatients')}");
A("                </button>");
A("              </div>");
A("            )}");
A("          </div>");
A("        </div>");
A("      )}");
A("");
A("      {confirmId !== null && (");
A("        <div className=\"fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm\">");
A("          <div className=\"bg-surface rounded-2xl shadow-2xl p-8 max-w-sm w-full mx-4 text-center\">");
A("            <div className=\"w-16 h-16 bg-amber-50 rounded-full flex items-center justify-center mx-auto mb-4\">");
A("              <span className=\"material-symbols-outlined text-amber-500 text-3xl\">inventory_2</span>");
A("            </div>");
A("            <h3 className=\"text-lg font-bold text-on-surface mb-2\">{t('pat_modalTitre')}</h3>");
A("            <p className=\"text-sm text-on-surface-variant mb-6\">");
A("              {t('pat_modalDesc')}");
A("            </p>");
A("            <div className=\"flex gap-3\">");
A("              <button onClick={() => setConfirmId(null)} className=\"flex-1 px-4 py-2.5 rounded-lg border border-outline-variant text-on-surface font-semibold text-sm hover:bg-surface-container-low\">");
A("                {t('pat_annuler')}");
A("              </button>");
A("              <button onClick={() => archiver(confirmId)} className=\"flex-1 px-4 py-2.5 rounded-lg bg-amber-500 text-white font-semibold text-sm hover:bg-amber-600 shadow-sm\">");
A("                {t('pat_confirmer')}");
A("              </button>");
A("            </div>");
A("          </div>");
A("        </div>");
A("      )}");
A("    </AppShell>");
A("  )");
A("}");

fs.writeFileSync('D:/chu_kine/projet_frontend/src/app/patients/page.tsx', lines.join('\n'), {encoding:'utf8'});
console.log('patients/page.tsx traduit avec succes !');
