const fs = require('fs');
const lines = [];
const A = (s) => lines.push(s);

A("'use client'");
A("");
A("import { useState, useEffect } from 'react'");
A("import Link from 'next/link'");
A("import AppShell from '@/components/layout/AppShell'");
A("import { useLanguage } from '@/context/LanguageContext'");
A("");
A("const API = process.env.NEXT_PUBLIC_API_URL");
A("");
A("const appointments = [");
A("  { id: 1, patientId: 101, time: '09:00', period: 'AM', name: 'Sarah Jenkins', motif: 'Suivi Post-operatoire - Genou', initials: 'SJ', avatarBg: 'bg-teal-100 text-teal-700' },");
A("  { id: 2, patientId: 102, time: '10:30', period: 'AM', name: 'Michael Chen', motif: 'Consultation Initial - Dos', initials: 'MC', avatarBg: 'bg-blue-100 text-blue-700' },");
A("  { id: 3, patientId: 103, time: '02:15', period: 'PM', name: 'Elena Rodriguez', motif: 'Reeducation - Epaule', initials: 'ER', avatarBg: 'bg-cyan-100 text-cyan-700' },");
A("]");
A("");
A("function toKey(d: Date) {");
A("  return d.getFullYear() + '-' + String(d.getMonth()+1).padStart(2,'0') + '-' + String(d.getDate()).padStart(2,'0')");
A("}");
A("");
A("export default function DashboardPage() {");
A("  const { t } = useLanguage()");
A("  const [rdvs, setRdvs]           = useState<any[]>([])");
A("  const [nbRdvAujourdhui, setNb]  = useState(0)");
A("  const [loading, setLoading]     = useState(true)");
A("");
A("  useEffect(() => {");
A("    fetch(API + '/rendezvous')");
A("      .then(r => r.json())");
A("      .then(data => {");
A("        if (Array.isArray(data)) {");
A("          setRdvs(data)");
A("          const today = toKey(new Date())");
A("          setNb(data.filter((r: any) => r.date === today).length)");
A("        }");
A("      })");
A("      .catch(() => {})");
A("      .finally(() => setLoading(false))");
A("  }, [])");
A("");
A("  return (");
A("    <AppShell searchPlaceholder=\"Rechercher un patient, un dossier...\">");
A("      <div className=\"mb-8\">");
A("        <h2 className=\"font-headline-md text-on-surface\">{t('dash_bonjour')}</h2>");
A("        <p className=\"font-body-lg text-on-surface-variant\">{t('dash_apercu')}</p>");
A("      </div>");
A("");
A("      <div className=\"grid grid-cols-1 lg:grid-cols-3 gap-8\">");
A("        <div className=\"lg:col-span-2 space-y-6\">");
A("");
A("          {/* RDV DU JOUR (mock) */}");
A("          <div className=\"bg-surface rounded-xl border border-outline-variant shadow-sm overflow-hidden\">");
A("            <div className=\"px-6 py-4 border-b border-outline-variant flex justify-between items-center bg-surface-container-low/50\">");
A("              <h4 className=\"font-title-sm text-on-surface\">{t('dash_rdvDuJour')}</h4>");
A("              <Link href=\"/calendrier\" className=\"text-primary font-semibold text-sm hover:underline\">{t('dash_voirTout')}</Link>");
A("            </div>");
A("            <div className=\"divide-y divide-outline-variant\">");
A("              {appointments.map((appt) => (");
A("                <Link key={appt.id} href={'/patients/' + appt.patientId + '?from=dashboard'}");
A("                  className=\"px-6 py-5 flex items-center gap-4 hover:bg-surface-container-low transition-colors\">");
A("                  <div className=\"text-center min-w-[60px]\">");
A("                    <p className=\"text-xs font-bold tracking-widest uppercase text-primary\">{appt.time}</p>");
A("                    <p className=\"text-xs text-on-surface-variant\">{appt.period}</p>");
A("                  </div>");
A("                  <div className={'w-12 h-12 rounded-full flex items-center justify-center flex-shrink-0 font-bold text-sm ' + appt.avatarBg}>");
A("                    {appt.initials}");
A("                  </div>");
A("                  <div className=\"flex-1\">");
A("                    <p className=\"font-semibold text-on-surface\">{appt.name}</p>");
A("                    <p className=\"text-sm text-on-surface-variant\">{appt.motif}</p>");
A("                  </div>");
A("                  <span className=\"material-symbols-outlined text-on-surface-variant text-lg flex-shrink-0\">chevron_right</span>");
A("                </Link>");
A("              ))}");
A("            </div>");
A("          </div>");
A("        </div>");
A("");
A("        {/* COLONNE DROITE */}");
A("        <div className=\"space-y-6\">");
A("");
A("          {/* CADRE RDV AUJOURD'HUI */}");
A("          <div className=\"bg-surface rounded-xl border border-outline-variant shadow-sm overflow-hidden\">");
A("            <div className=\"px-6 py-4 border-b border-outline-variant bg-surface-container-low/50 flex items-center gap-2\">");
A("              <span className=\"material-symbols-outlined text-primary\">today</span>");
A("              <h4 className=\"font-title-sm text-on-surface\">Rendez-vous aujourd'hui</h4>");
A("            </div>");
A("            <div className=\"p-6 flex flex-col items-center justify-center gap-3\">");
A("              {loading ? (");
A("                <div className=\"w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin\"></div>");
A("              ) : (");
A("                <>"); 
A("                  <div className=\"w-24 h-24 rounded-full bg-teal-50 border-4 border-primary flex items-center justify-center\">");
A("                    <span className=\"text-4xl font-bold text-primary\">{nbRdvAujourdhui}</span>");
A("                  </div>");
A("                  <p className=\"text-sm font-semibold text-on-surface-variant text-center\">");
A("                    {nbRdvAujourdhui === 0 ? 'Aucun rendez-vous aujourd\\'hui' : nbRdvAujourdhui === 1 ? '1 rendez-vous prévu ce jour' : nbRdvAujourdhui + ' rendez-vous prévus ce jour'}");
A("                  </p>");
A("                  <Link href=\"/calendrier\"");
A("                    className=\"mt-2 flex items-center gap-1.5 px-4 py-2 rounded-lg bg-primary text-white text-sm font-semibold hover:opacity-90 transition\">");
A("                    <span className=\"material-symbols-outlined text-sm\">calendar_today</span>");
A("                    Voir le calendrier");
A("                  </Link>");
A("                </>");
A("              )}");
A("            </div>");
A("          </div>");
A("");
A("          {/* ACCES RAPIDE RAPPORT */}");
A("          <div className=\"bg-surface rounded-xl border border-outline-variant shadow-sm overflow-hidden\">");
A("            <div className=\"px-6 py-4 border-b border-outline-variant bg-surface-container-low/50 flex items-center gap-2\">");
A("              <span className=\"material-symbols-outlined text-primary\">assessment</span>");
A("              <h4 className=\"font-title-sm text-on-surface\">Rapport d'activité</h4>");
A("            </div>");
A("            <div className=\"p-6 flex flex-col items-center gap-3\">");
A("              <span className=\"material-symbols-outlined text-5xl text-primary/30\">bar_chart</span>");
A("              <p className=\"text-sm text-on-surface-variant text-center\">Consultez le rapport complet de votre activité</p>");
A("              <Link href=\"/rapport\"");
A("                className=\"flex items-center gap-1.5 px-4 py-2 rounded-lg bg-primary text-white text-sm font-semibold hover:opacity-90 transition\">");
A("                <span className=\"material-symbols-outlined text-sm\">assessment</span>");
A("                Voir le rapport");
A("              </Link>");
A("            </div>");
A("          </div>");
A("");
A("        </div>");
A("      </div>");
A("    </AppShell>");
A("  )");
A("}");

fs.writeFileSync('D:/chu_kine/projet_frontend/src/app/page.tsx', lines.join('\n'), {encoding:'utf8'});
console.log('Dashboard mis a jour avec succes !');
