const fs = require('fs');
const lines = [];
const A = (s) => lines.push(s);

A("'use client'");
A("");
A("import { useState, useEffect, useMemo } from 'react'");
A("import Sidebar from '@/components/layout/Sidebar'");
A("import TopBar from '@/components/layout/TopBar'");
A("import { useLanguage } from '@/context/LanguageContext'");
A("");
A("const API = process.env.NEXT_PUBLIC_API_URL");
A("const HOURS = ['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00']");
A("");
A("interface Patient {");
A("  id: number; nom: string; prenom: string; dateNaissance?: string; sexe?: string");
A("  diagnostic?: string; statut?: string; numeroDossier?: string; dateAdmission?: string");
A("}");
A("");
A("interface RendezVous {");
A("  id: number; date: string; heureDebut: string; heureFin: string");
A("  motif: string; type: string; statut: string; patientId: number");
A("  patient?: Patient");
A("}");
A("");
A("const TYPE_COLOR: Record<string, string> = {");
A("  consultation: 'bg-teal-50 border-teal-500 text-teal-800',");
A("  soin:         'bg-blue-100 border-blue-500 text-blue-800',");
A("  bilan:        'bg-purple-50 border-purple-500 text-purple-800',");
A("  exercice:     'bg-amber-50 border-amber-500 text-amber-800',");
A("}");
A("");
A("const STATUT_COLOR: Record<string, string> = {");
A("  actif:      'bg-emerald-100 text-emerald-700',");
A("  inactif:    'bg-slate-100 text-slate-500',");
A("  en_attente: 'bg-amber-100 text-amber-700',");
A("  archive:    'bg-red-100 text-red-500',");
A("}");
A("");
A("function toKey(d: Date) { return d.getFullYear() + '-' + String(d.getMonth()+1).padStart(2,'0') + '-' + String(d.getDate()).padStart(2,'0') }");
A("function addDays(d: Date, n: number) { const r = new Date(d); r.setDate(r.getDate()+n); return r }");
A("function startOfWeek(d: Date) { const r = new Date(d); const day = r.getDay(); const diff = day===0?-6:1-day; r.setDate(r.getDate()+diff); return r }");
A("function startOfMonth(d: Date) { return new Date(d.getFullYear(), d.getMonth(), 1) }");
A("function heureToIndex(h: string) { if (!h) return 0; return HOURS.indexOf(h.substring(0,5)) }");
A("");
A("type View = 'jour' | 'semaine' | 'mois'");
A("");
A("export default function CalendrierPage() {");
A("  const { t } = useLanguage()");
A("");
A("  const DAYS_SHORT = [t('cal_lun'),t('cal_mar'),t('cal_mer'),t('cal_jeu'),t('cal_ven'),t('cal_sam'),t('cal_dim')]");
A("  const MONTHS = [t('cal_janvier'),t('cal_fevrier'),t('cal_mars'),t('cal_avril'),t('cal_mai'),t('cal_juin'),t('cal_juillet'),t('cal_aout'),t('cal_septembre'),t('cal_octobre'),t('cal_novembre'),t('cal_decembre')]");
A("");
A("  const [view, setView]               = useState<View>('semaine')");
A("  const [current, setCurrent]         = useState(new Date())");
A("  const [drawerOpen, setDrawerOpen]   = useState(false)");
A("  const [rdvs, setRdvs]               = useState<RendezVous[]>([])");
A("  const [loading, setLoading]         = useState(true)");
A("  const [selectedRdv, setSelectedRdv] = useState<RendezVous | null>(null)");
A("  const [selectedPatient, setSelectedPatient] = useState<Patient | null>(null)");
A("  const [patientLoading, setPatientLoading]   = useState(false)");
A("");
A("  useEffect(() => {");
A("    fetch(API + '/rendezvous')");
A("      .then(r => r.json())");
A("      .then(data => { if (Array.isArray(data)) setRdvs(data) })");
A("      .catch(() => {})");
A("      .finally(() => setLoading(false))");
A("  }, [])");
A("");
A("  async function selectRdv(rdv: RendezVous) {");
A("    setSelectedRdv(rdv)");
A("    setDrawerOpen(true)");
A("    setPatientLoading(true)");
A("    try {");
A("      const res = await fetch(API + '/patients/' + rdv.patientId)");
A("      const data = await res.json()");
A("      setSelectedPatient(data)");
A("    } catch {");
A("      setSelectedPatient(rdv.patient || null)");
A("    } finally {");
A("      setPatientLoading(false)");
A("    }");
A("  }");
A("");
A("  function navigate(dir: number) {");
A("    const d = new Date(current)");
A("    if (view==='jour')    d.setDate(d.getDate()+dir)");
A("    if (view==='semaine') d.setDate(d.getDate()+dir*7)");
A("    if (view==='mois')    d.setMonth(d.getMonth()+dir)");
A("    setCurrent(d)");
A("  }");
A("");
A("  const title = useMemo(() => {");
A("    if (view==='jour') return DAYS_SHORT[current.getDay()===0?6:current.getDay()-1] + ' ' + current.getDate() + ' ' + MONTHS[current.getMonth()] + ' ' + current.getFullYear()");
A("    if (view==='semaine') { const s=startOfWeek(current); const e=addDays(s,6); return t('cal_semaineDu') + ' ' + s.getDate() + ' - ' + e.getDate() + ' ' + MONTHS[e.getMonth()] + ' ' + e.getFullYear() }");
A("    return MONTHS[current.getMonth()] + ' ' + current.getFullYear()");
A("  }, [view, current, t])");
A("");
A("  const weekDays  = useMemo(() => { const s=startOfWeek(current); return Array.from({length:7},(_,i)=>addDays(s,i)) }, [current])");
A("  const monthGrid = useMemo(() => { const first=startOfMonth(current); const dow=first.getDay()===0?6:first.getDay()-1; const start=addDays(first,-dow); return Array.from({length:42},(_,i)=>addDays(start,i)) }, [current])");
A("");
A("  const apptForDay = (key: string) => rdvs.filter(r => r.date === key)");
A("  const colorOf    = (r: RendezVous) => TYPE_COLOR[r.type] || 'bg-slate-100 border-slate-400 text-slate-700'");
A("  const patientName= (r: RendezVous) => r.patient ? r.patient.prenom + ' ' + r.patient.nom : '-'");
A("  const today      = toKey(new Date())");
A("");
A("  function RdvCard({ a, style, small }: { a: RendezVous; style?: React.CSSProperties; small?: boolean }) {");
A("    return (");
A("      <div");
A("        onClick={() => selectRdv(a)}");
A("        className={'border-l-4 rounded-r shadow-sm cursor-pointer transition-all hover:scale-[1.02] hover:shadow-md ' + (selectedRdv?.id===a.id ? 'ring-2 ring-primary scale-[1.02] ' : '') + colorOf(a) + (small ? ' p-1.5' : ' p-3')}");
A("        style={style}");
A("      >");
A("        <p className={'font-bold truncate ' + (small?'text-[10px]':'text-xs')}>{a.motif}</p>");
A("        <p className={'opacity-80 mt-0.5 truncate ' + (small?'text-[9px]':'text-[10px]')}>{patientName(a)}</p>");
A("        {!small && <p className=\"text-[10px] opacity-70 mt-0.5\">{a.heureDebut?.substring(0,5)} - {a.heureFin?.substring(0,5)}</p>}");
A("      </div>");
A("    )");
A("  }");
A("");
A("  return (");
A("    <div className=\"flex min-h-screen bg-background\">");
A("      <Sidebar />");
A("      <div className=\"flex-1 ml-64 flex flex-col min-h-screen\">");
A("        <TopBar searchPlaceholder={t('cal_rechercherPlaceholder')} />");
A("        <div className=\"flex flex-1 overflow-hidden\">");
A("          <section className=\"flex-1 overflow-auto\">");
A("");
A("            <div className=\"sticky top-0 z-30 bg-surface/90 backdrop-blur-sm border-b border-outline-variant px-6 py-3 flex justify-between items-center\">");
A("              <div className=\"flex items-center gap-2\">");
A("                <button onClick={() => navigate(-1)} className=\"w-8 h-8 rounded-lg border border-outline-variant flex items-center justify-center hover:bg-surface-container-low transition-colors\">");
A("                  <span className=\"material-symbols-outlined text-sm\">chevron_left</span>");
A("                </button>");
A("                <h3 className=\"font-semibold text-on-surface px-2 text-sm\">{title}</h3>");
A("                <button onClick={() => navigate(1)} className=\"w-8 h-8 rounded-lg border border-outline-variant flex items-center justify-center hover:bg-surface-container-low transition-colors\">");
A("                  <span className=\"material-symbols-outlined text-sm\">chevron_right</span>");
A("                </button>");
A("              </div>");
A("              <div className=\"flex items-center gap-3\">");
A("                <div className=\"flex rounded-lg border border-outline-variant overflow-hidden text-sm\">");
A("                  {(['jour','semaine','mois'] as View[]).map((v) => (");
A("                    <button key={v} onClick={() => setView(v)}");
A("                      className={'px-3 py-1.5 font-semibold transition-colors capitalize ' + (view===v?'bg-primary text-white':'text-on-surface-variant hover:bg-surface-container-low')}>");
A("                      {v==='jour'?t('cal_jour'):v==='semaine'?t('cal_semaine'):t('cal_mois')}");
A("                    </button>");
A("                  ))}");
A("                </div>");
A("                <button className=\"btn-primary text-sm px-4 py-2 flex items-center gap-1\">");
A("                  <span className=\"material-symbols-outlined text-sm\">add</span>");
A("                  {t('cal_nouveauRdv')}");
A("                </button>");
A("              </div>");
A("            </div>");
A("");
A("            {loading ? (");
A("              <div className=\"flex flex-col items-center justify-center py-24 text-on-surface-variant\">");
A("                <div className=\"w-10 h-10 border-4 border-primary border-t-transparent rounded-full animate-spin mb-4\"></div>");
A("                <p className=\"text-sm\">{t('cal_chargement')}</p>");
A("              </div>");
A("            ) : (");
A("              <>");
A("                {view==='jour' && (() => {");
A("                  const key = toKey(current)");
A("                  const appts = apptForDay(key)");
A("                  return (");
A("                    <div className=\"min-w-[400px]\">");
A("                      <div className=\"border-b border-outline-variant bg-surface sticky top-[57px] z-20 px-6 py-3 text-center\">");
A("                        <p className=\"text-xs text-on-surface-variant font-semibold uppercase tracking-wider\">{DAYS_SHORT[current.getDay()===0?6:current.getDay()-1]}</p>");
A("                        <p className=\"text-2xl font-bold text-primary\">{current.getDate()}</p>");
A("                        <p className=\"text-xs text-on-surface-variant\">{appts.length} {t('cal_rendezVous').toLowerCase()}</p>");
A("                      </div>");
A("                      <div className=\"relative\">");
A("                        {HOURS.map((h, hi) => (");
A("                          <div key={h} className=\"flex border-b border-outline-variant min-h-[80px]\">");
A("                            <div className=\"w-20 flex-shrink-0 p-3 border-r border-outline-variant flex items-start justify-end pr-3\">");
A("                              <span className=\"text-[11px] text-on-surface-variant font-semibold\">{h}</span>");
A("                            </div>");
A("                            <div className=\"flex-1 hover:bg-surface-container-low/30 transition-colors relative\">");
A("                              {appts.filter(a => heureToIndex(a.heureDebut)===hi).map(a => (");
A("                                <RdvCard key={a.id} a={a}");
A("                                  style={{ position:'absolute', left:'8px', right:'8px', top:'4px',");
A("                                    height:(Math.max(1,heureToIndex(a.heureFin)-heureToIndex(a.heureDebut))*80-8) + 'px' }} />");
A("                              ))}");
A("                            </div>");
A("                          </div>");
A("                        ))}");
A("                        {appts.length===0 && (");
A("                          <div className=\"flex flex-col items-center justify-center py-24 text-on-surface-variant\">");
A("                            <span className=\"material-symbols-outlined text-4xl mb-2\">event_busy</span>");
A("                            <p className=\"text-sm\">{t('cal_aucunRdvJour')}</p>");
A("                          </div>");
A("                        )}");
A("                      </div>");
A("                    </div>");
A("                  )");
A("                })()}");
A("");
A("                {view==='semaine' && (");
A("                  <div className=\"min-w-[700px]\">");
A("                    <div className=\"grid border-b border-outline-variant bg-surface sticky top-[57px] z-20\" style={{gridTemplateColumns:'80px repeat(7,1fr)'}}>") ;
A("                      <div className=\"p-3 border-r border-outline-variant\" />");
A("                      {weekDays.map((d) => {");
A("                        const k = toKey(d)");
A("                        const isToday = k===today");
A("                        return (");
A("                          <div key={k} onClick={() => { setCurrent(d); setView('jour') }}");
A("                            className={'p-3 text-center border-r border-outline-variant last:border-r-0 cursor-pointer hover:bg-primary/5 transition-colors ' + (isToday?'bg-primary/5':'')}>");
A("                            <p className=\"text-xs text-on-surface-variant font-semibold uppercase tracking-wider\">{DAYS_SHORT[d.getDay()===0?6:d.getDay()-1]}</p>");
A("                            <p className={'text-lg font-bold mt-0.5 ' + (isToday?'text-primary':'text-on-surface')}>{d.getDate()}</p>");
A("                            <p className=\"text-[10px] text-on-surface-variant\">{apptForDay(k).length>0?apptForDay(k).length+' RDV':''}</p>");
A("                          </div>");
A("                        )");
A("                      })}");
A("                    </div>");
A("                    <div className=\"relative\">");
A("                      {HOURS.map((h, hi) => (");
A("                        <div key={h} className=\"border-b border-outline-variant min-h-[80px]\" style={{display:'grid',gridTemplateColumns:'80px repeat(7,1fr)'}}>") ;
A("                          <div className=\"p-3 border-r border-outline-variant flex items-start justify-end pr-3\">");
A("                            <span className=\"text-[11px] text-on-surface-variant font-semibold\">{h}</span>");
A("                          </div>");
A("                          {weekDays.map((d) => {");
A("                            const k = toKey(d)");
A("                            const isToday = k===today");
A("                            const appts = apptForDay(k).filter(a => heureToIndex(a.heureDebut)===hi)");
A("                            return (");
A("                              <div key={k} className={'border-r border-outline-variant last:border-r-0 relative ' + (isToday?'bg-primary/5':'')}>") ;
A("                                {appts.map(a => (");
A("                                  <RdvCard key={a.id} a={a} small");
A("                                    style={{ position:'absolute', left:'2px', right:'2px', top:'4px',");
A("                                      height:(Math.max(1,heureToIndex(a.heureFin)-heureToIndex(a.heureDebut))*80-8) + 'px' }} />");
A("                                ))}");
A("                              </div>");
A("                            )");
A("                          })}");
A("                        </div>");
A("                      ))}");
A("                      <div className=\"absolute left-0 right-0 h-[2px] bg-red-500 z-20 pointer-events-none flex items-center\" style={{top:'280px'}}>");
A("                        <div className=\"w-3 h-3 rounded-full bg-red-500 ml-20 -translate-x-1/2\" />");
A("                      </div>");
A("                    </div>");
A("                  </div>");
A("                )}");
A("");
A("                {view==='mois' && (");
A("                  <div className=\"p-4\">");
A("                    <div className=\"grid grid-cols-7 mb-1\">");
A("                      {DAYS_SHORT.map(d => (");
A("                        <div key={d} className=\"text-center text-xs font-semibold text-on-surface-variant uppercase tracking-wider py-2\">{d}</div>");
A("                      ))}");
A("                    </div>");
A("                    <div className=\"grid grid-cols-7 gap-1\">");
A("                      {monthGrid.map((d) => {");
A("                        const k = toKey(d)");
A("                        const isCurrentMonth = d.getMonth()===current.getMonth()");
A("                        const isToday = k===today");
A("                        const appts = apptForDay(k)");
A("                        return (");
A("                          <div key={k}");
A("                            className={'min-h-[90px] rounded-xl border p-2 transition-colors ' + (isCurrentMonth?'bg-surface border-outline-variant':'bg-surface-container-low border-outline-variant') + (isToday?' border-primary ring-2 ring-primary/20':'')}>") ;
A("                            <p onClick={() => { setCurrent(d); setView('jour') }}");
A("                              className={'text-xs font-bold mb-1 w-6 h-6 flex items-center justify-center rounded-full cursor-pointer hover:bg-primary/10 ' + (isToday?'bg-primary text-white':isCurrentMonth?'text-on-surface':'text-on-surface-variant')}>");
A("                              {d.getDate()}");
A("                            </p>");
A("                            <div className=\"space-y-0.5\">");
A("                              {appts.slice(0,2).map(a => (");
A("                                <div key={a.id} onClick={() => selectRdv(a)}");
A("                                  className={'text-[9px] font-semibold px-1.5 py-0.5 rounded truncate border-l-2 cursor-pointer hover:opacity-80 transition-opacity ' + colorOf(a) + (selectedRdv?.id===a.id?' ring-1 ring-primary':'')}>") ;
A("                                  {a.motif}");
A("                                </div>");
A("                              ))}");
A("                              {appts.length>2 && (");
A("                                <p onClick={() => { setCurrent(d); setView('jour') }}");
A("                                  className=\"text-[9px] text-on-surface-variant font-semibold pl-1 cursor-pointer hover:text-primary\">");
A("                                  +{appts.length-2} {t('cal_autres')}");
A("                                </p>");
A("                              )}");
A("                            </div>");
A("                          </div>");
A("                        )");
A("                      })}");
A("                    </div>");
A("                  </div>");
A("                )}");
A("              </>");
A("            )}");
A("          </section>");
A("");
A("          {drawerOpen && (");
A("            <aside className=\"w-96 border-l border-outline-variant bg-surface overflow-y-auto flex flex-col flex-shrink-0\">");
A("              <div className=\"p-6 border-b border-outline-variant flex justify-between items-center bg-surface-container-lowest\">");
A("                <h3 className=\"font-semibold text-primary\">{t('cal_profilPatient')}</h3>");
A("                <button onClick={() => { setDrawerOpen(false); setSelectedRdv(null); setSelectedPatient(null) }}");
A("                  className=\"text-on-surface-variant hover:text-on-surface transition-colors\">");
A("                  <span className=\"material-symbols-outlined\">close</span>");
A("                </button>");
A("              </div>");
A("");
A("              {patientLoading ? (");
A("                <div className=\"flex flex-col items-center justify-center flex-1 py-16 text-on-surface-variant\">");
A("                  <div className=\"w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin mb-3\"></div>");
A("                  <p className=\"text-xs\">{t('cal_chargementProfil')}</p>");
A("                </div>");
A("              ) : selectedPatient ? (");
A("                <>");
A("                  <div className=\"p-8 text-center border-b border-outline-variant\">");
A("                    <div className=\"relative inline-block\">");
A("                      <div className=\"w-24 h-24 rounded-full mx-auto border-4 border-surface shadow-lg bg-primary/10 flex items-center justify-center\">");
A("                        <span className=\"text-3xl font-bold text-primary\">");
A("                          {selectedPatient.prenom?.[0]}{selectedPatient.nom?.[0]}");
A("                        </span>");
A("                      </div>");
A("                      <span className=\"absolute bottom-1 right-1 w-5 h-5 bg-green-500 border-2 border-surface rounded-full\" />");
A("                    </div>");
A("                    <a href={'/patients/' + selectedPatient.id + '?from=calendrier'} className=\"mt-4 font-bold text-primary text-lg hover:underline cursor-pointer block\">{selectedPatient.prenom} {selectedPatient.nom}</a>");
A("                    <div className=\"flex items-center justify-center gap-2 mt-2\">");
A("                      <span className={'text-[11px] font-bold px-2 py-0.5 rounded-full ' + (STATUT_COLOR[selectedPatient.statut||''] || 'bg-surface-container-low text-on-surface-variant')}>");
A("                        {(selectedPatient.statut||'').toUpperCase()}");
A("                      </span>");
A("                      <span className=\"text-on-surface-variant text-xs\">•</span>");
A("                      <span className=\"text-on-surface-variant text-xs\">{selectedPatient.numeroDossier || 'ID: #' + selectedPatient.id}</span>");
A("                    </div>");
A("                  </div>");
A("");
A("                  {selectedRdv && (");
A("                    <div className=\"px-6 pt-5\">");
A("                      <div className={'rounded-xl p-4 border-l-4 ' + colorOf(selectedRdv)}>");
A("                        <div className=\"flex items-center gap-2 mb-2\">");
A("                          <span className=\"material-symbols-outlined text-sm\">event</span>");
A("                          <h5 className=\"text-xs font-bold uppercase tracking-wider\">{t('cal_rendezVous')}</h5>");
A("                        </div>");
A("                        <p className=\"text-sm font-bold\">{selectedRdv.motif}</p>");
A("                        <p className=\"text-xs opacity-80 mt-1\">{selectedRdv.date} · {selectedRdv.heureDebut?.substring(0,5)} - {selectedRdv.heureFin?.substring(0,5)}</p>");
A("                        <span className=\"inline-block mt-2 text-[10px] font-bold px-2 py-0.5 rounded-full bg-white/60\">{selectedRdv.type}</span>");
A("                      </div>");
A("                    </div>");
A("                  )}");
A("");
A("                  <div className=\"px-6 py-5 space-y-5\">");
A("                    <div className=\"bg-surface-container-low rounded-xl p-5 border border-outline-variant\">");
A("                      <div className=\"flex items-center gap-2 mb-3\">");
A("                        <span className=\"material-symbols-outlined text-primary text-lg\">medical_information</span>");
A("                        <h5 className=\"text-xs font-bold text-primary uppercase tracking-wider\">{t('cal_resumeMedical')}</h5>");
A("                      </div>");
A("                      <div className=\"space-y-2\">");
A("                        {[");
A("                          { label: t('cal_diagnostic'),    value: selectedPatient.diagnostic || '-' },");
A("                          { label: t('cal_dateAdmission'), value: selectedPatient.dateAdmission || '-' },");
A("                          { label: t('cal_sexe'),          value: selectedPatient.sexe==='M'?t('cal_homme'): selectedPatient.sexe==='F'?t('cal_femme'): '-' },");
A("                        ].map(item => (");
A("                          <div key={item.label} className=\"flex justify-between\">");
A("                            <span className=\"text-xs text-on-surface-variant\">{item.label}</span>");
A("                            <span className=\"text-xs font-semibold text-primary\">{item.value}</span>");
A("                          </div>");
A("                        ))}");
A("                      </div>");
A("                    </div>");
A("                    <button className=\"w-full btn-primary flex items-center justify-center gap-2\">");
A("                      <span className=\"material-symbols-outlined text-sm\">add_circle</span>");
A("                      {t('cal_nouveauCompteRendu')}");
A("                    </button>");
A("                  </div>");
A("                </>");
A("              ) : (");
A("                <div className=\"flex flex-col items-center justify-center flex-1 py-16 text-on-surface-variant\">");
A("                  <span className=\"material-symbols-outlined text-5xl mb-3\">person_search</span>");
A("                  <p className=\"text-sm\">{t('cal_cliquezRdv')}</p>");
A("                  <p className=\"text-xs mt-1\">{t('cal_pourVoirProfil')}</p>");
A("                </div>");
A("              )}");
A("            </aside>");
A("          )}");
A("        </div>");
A("      </div>");
A("");
A("      <button");
A("        className={'fixed bottom-8 z-30 w-14 h-14 bg-primary text-white rounded-full shadow-2xl flex items-center justify-center hover:scale-105 active:scale-95 transition-all ' + (drawerOpen?'right-[416px]':'right-8')}");
A("        onClick={() => setDrawerOpen(true)}>");
A("        <span className=\"material-symbols-outlined text-2xl\">add</span>");
A("      </button>");
A("    </div>");
A("  )");
A("}");

fs.writeFileSync('D:/chu_kine/projet_frontend/src/app/calendrier/page.tsx', lines.join('\n'), {encoding:'utf8'});
console.log('calendrier/page.tsx traduit avec succes !');
