const fs = require('fs');
const lines = [];
const A = (s) => lines.push(s);

A("'use client'");
A("");
A("import { useState, useEffect } from 'react'");
A("import { useSearchParams } from 'next/navigation'");
A("import Link from 'next/link'");
A("import { useRouter } from 'next/navigation'");
A("import AppShell from '@/components/layout/AppShell'");
A("");
A("const API = process.env.NEXT_PUBLIC_API_URL");
A("");
A("interface Patient {");
A("  id: number; numeroDossier: string; nom: string; prenom: string");
A("  dateNaissance: string; sexe: string; adresse: string; telephone: string");
A("  diagnostic: string; statut: string; dateAdmission: string");
A("  dateDerniereVisite: string; antecedents: string");
A("}");
A("");
A("interface HistoriqueEntry { date: string; heure: string; texte: string }");
A("");
A("const MOCK_PATIENTS: Record<number, Patient> = {");
A("  1:   { id: 1,   numeroDossier: 'P-2024-001', nom: 'Rakoto', prenom: 'Jean', dateNaissance: '1985-03-12', sexe: 'M', adresse: 'Fianarantsoa', telephone: '+261 34 00 000 01', diagnostic: 'Rupture LCA genou droit', statut: 'actif', dateAdmission: '2024-04-12', dateDerniereVisite: '2024-06-08', antecedents: 'Aucun antecedent' },");
A("  2:   { id: 2,   numeroDossier: 'P-2024-002', nom: 'Rabe', prenom: 'Marie', dateNaissance: '1992-07-23', sexe: 'F', adresse: 'Fianarantsoa', telephone: '+261 34 00 000 02', diagnostic: 'Tendinite calcifiante epaule droite', statut: 'actif', dateAdmission: '2024-04-18', dateDerniereVisite: '2024-06-05', antecedents: 'Aucun antecedent' },");
A("  3:   { id: 3,   numeroDossier: 'P-2024-003', nom: 'Andria', prenom: 'Paul', dateNaissance: '1978-11-08', sexe: 'M', adresse: 'Fianarantsoa', telephone: '+261 34 00 000 03', diagnostic: 'Entorse cheville gauche grade 2', statut: 'actif', dateAdmission: '2024-04-22', dateDerniereVisite: '2024-06-09', antecedents: 'Aucun antecedent' },");
A("  4:   { id: 4,   numeroDossier: 'P-2024-004', nom: 'Rasoa', prenom: 'Lala', dateNaissance: '1965-05-30', sexe: 'F', adresse: 'Fianarantsoa', telephone: '+261 34 00 000 04', diagnostic: 'Arthrose lombaire chronique', statut: 'actif', dateAdmission: '2024-05-02', dateDerniereVisite: '', antecedents: 'Aucun antecedent' },");
A("  5:   { id: 5,   numeroDossier: 'P-2024-005', nom: 'Rakotonirina', prenom: 'Zo', dateNaissance: '2001-09-15', sexe: 'F', adresse: 'Fianarantsoa', telephone: '+261 34 00 000 05', diagnostic: 'Scoliose thoracique', statut: 'inactif', dateAdmission: '2024-03-10', dateDerniereVisite: '2024-05-28', antecedents: 'Aucun antecedent' },");
A("  6:   { id: 6,   numeroDossier: 'P-2024-006', nom: 'Randriamihaingo', prenom: 'Tiana', dateNaissance: '1988-02-20', sexe: 'F', adresse: 'Fianarantsoa', telephone: '+261 34 00 000 06', diagnostic: 'Paralysie faciale peripherique droite', statut: 'en_attente', dateAdmission: '2024-06-08', dateDerniereVisite: '', antecedents: 'Aucun antecedent' },");
A("  101: { id: 101, numeroDossier: 'P-2024-101', nom: 'Jenkins', prenom: 'Sarah', dateNaissance: '1990-05-14', sexe: 'F', adresse: 'Fianarantsoa', telephone: '+261 34 00 001 01', diagnostic: 'Suivi Post-operatoire Genou', statut: 'actif', dateAdmission: '2024-03-01', dateDerniereVisite: '2024-06-10', antecedents: 'Operation genou droit mars 2024' },");
A("  102: { id: 102, numeroDossier: 'P-2024-102', nom: 'Chen', prenom: 'Michael', dateNaissance: '1983-11-22', sexe: 'M', adresse: 'Fianarantsoa', telephone: '+261 34 00 001 02', diagnostic: 'Consultation Initial Dos', statut: 'en_attente', dateAdmission: '2024-06-09', dateDerniereVisite: '', antecedents: 'Douleurs lombaires chroniques' },");
A("  103: { id: 103, numeroDossier: 'P-2024-103', nom: 'Rodriguez', prenom: 'Elena', dateNaissance: '1981-03-08', sexe: 'F', adresse: 'Fianarantsoa', telephone: '+261 34 00 001 03', diagnostic: 'Reeducation Epaule', statut: 'actif', dateAdmission: '2024-04-15', dateDerniereVisite: '2024-06-12', antecedents: 'Rupture partielle coiffe des rotateurs' },");
A("}");
A("");
A("function getNow() {");
A("  const now = new Date()");
A("  const date = now.getDate() + ' ' + now.toLocaleDateString('fr-FR',{month:'long'}) + ' ' + now.getFullYear()");
A("  const heure = String(now.getHours()).padStart(2,'0') + 'h' + String(now.getMinutes()).padStart(2,'0')");
A("  return { date, heure }");
A("}");
A("");
A("const TYPES = ['consultation','bilan','soin','exercice']");
A("const TYPE_COLOR: Record<string,string> = {");
A("  consultation: 'bg-teal-100 text-teal-700 border-teal-300',");
A("  bilan:        'bg-purple-100 text-purple-700 border-purple-300',");
A("  soin:         'bg-blue-100 text-blue-700 border-blue-300',");
A("  exercice:     'bg-amber-100 text-amber-700 border-amber-300',");
A("}");
A("");
A("function ChampLibre({ label, value, onChange, placeholder, icon, rows=3, locked=false, accent='slate' }: {");
A("  label: string; value: string; onChange: (v:string)=>void");
A("  placeholder?: string; icon?: string; rows?: number; locked?: boolean; accent?: string");
A("}) {");
A("  return (");
A("    <div>");
A("      <label className=\"text-xs font-bold text-slate-500 uppercase tracking-widest block mb-1 flex items-center gap-1\">");
A("        {icon && <span className=\"material-symbols-outlined text-sm\" style={{color:'inherit'}}>{icon}</span>}");
A("        {label}");
A("      </label>");
A("      <textarea value={value} onChange={e => !locked && onChange(e.target.value)} rows={rows}");
A("        disabled={locked}");
A("        className={'w-full p-3 rounded-lg border text-sm resize-none outline-none transition-all ' + (locked ? 'bg-white/60 border-white/40 text-slate-500 cursor-not-allowed' : 'bg-white/70 border-white/50 focus:border-white focus:ring-1 focus:ring-white/80')}");
A("        placeholder={locked ? '' : (placeholder || 'Saisir...')} />");
A("    </div>");
A("  )");
A("}");
A("");
A("function SectionHistorique({ label, icon, value, onChange, historique, onEnregistrer, bgClass, borderClass, titleColor, histoBg, histoBorder, histoTimeColor, locked=false }: {");
A("  label: string; icon: string; value: string; onChange: (v:string)=>void");
A("  historique: HistoriqueEntry[]; onEnregistrer: ()=>void");
A("  bgClass: string; borderClass: string; titleColor: string");
A("  histoBg: string; histoBorder: string; histoTimeColor: string");
A("  locked?: boolean");
A("}) {");
A("  return (");
A("    <div className={'rounded-xl shadow-sm border p-6 ' + bgClass + ' ' + borderClass}>");
A("      <h3 className={'font-headline-md flex items-center gap-2 mb-4 ' + titleColor}>");
A("        <span className=\"material-symbols-outlined\">{icon}</span>");
A("        {label}");
A("        {locked && <span className=\"ml-auto text-xs bg-white/60 px-2 py-0.5 rounded-full font-semibold flex items-center gap-1\"><span className=\"material-symbols-outlined text-sm\">lock</span>Validé</span>}");
A("      </h3>");
A("      {!locked && (");
A("        <div className=\"relative mb-3\">");
A("          <textarea value={value} onChange={e => onChange(e.target.value)} rows={3}");
A("            className=\"w-full p-4 rounded-lg bg-white/70 border border-white/50 focus:border-white focus:ring-1 focus:ring-white/80 text-sm resize-none outline-none pb-12\"");
A("            placeholder={'Saisir ' + label.toLowerCase() + '...'} />");
A("          <div className=\"absolute bottom-3 right-3\">");
A("            <button onClick={onEnregistrer}");
A("              className=\"bg-white/80 text-slate-700 px-4 py-1.5 rounded-lg text-sm font-semibold shadow hover:bg-white transition\">");
A("              Enregistrer");
A("            </button>");
A("          </div>");
A("        </div>");
A("      )}");
A("      {historique.length > 0 && (");
A("        <div className=\"mt-3 space-y-2\">");
A("          <p className=\"text-xs font-bold uppercase tracking-widest opacity-60\">Historique</p>");
A("          {historique.map((h, i) => (");
A("            <div key={i} className={'rounded-lg p-3 border ' + histoBg + ' ' + histoBorder}>");
A("              <p className={'text-[10px] font-semibold mb-1 ' + histoTimeColor}>{h.date} — {h.heure}</p>");
A("              <p className=\"text-sm text-slate-700\">{h.texte}</p>");
A("            </div>");
A("          ))}");
A("        </div>");
A("      )}");
A("      {historique.length === 0 && locked && (");
A("        <p className=\"text-sm opacity-50 italic\">Aucune entrée enregistrée</p>");
A("      )}");
A("    </div>");
A("  )");
A("}");
A("");
A("export default function PatientProfilePage({ params }: { params: { id: string } }) {");
A("  const [patient, setPatient]         = useState<Patient | null>(null)");
A("  const [loading, setLoading]         = useState(true)");
A("  const [valide, setValide]           = useState(false)");
A("  const [showConfirm, setShowConfirm] = useState(false)");
A("  const searchParams = useSearchParams()");
A("  const router = useRouter()");
A("  const from = searchParams.get('from')");
A("");
A("  const [heureDebut, setHeureDebut]     = useState('')");
A("  const [heureFin, setHeureFin]         = useState('')");
A("  const [typeRdv, setTypeRdv]           = useState('')");
A("  const [showTypeMenu, setShowTypeMenu] = useState(false)");
A("  const [religion, setReligion]         = useState('')");
A("  const [modeAdmission, setModeAdmission] = useState('')");
A("  const [autoRefere, setAutoRefere]       = useState('')");
A("  const [referePar, setReferePar]         = useState('')");
A("  const [objectif, setObjectif]           = useState('')");
A("  const [antecedents, setAntecedents]           = useState('')");
A("  const [historieMaladie, setHistorieMaladie]   = useState('')");
A("  const [bilanFonctionnel, setBilanFonctionnel] = useState('')");
A("  const [bilanIncapacite, setBilanIncapacite]   = useState('')");
A("  const [diagnosticKine, setDiagnosticKine]     = useState('')");
A("  const [traitement, setTraitement]             = useState('')");
A("  const [historiqueTraitement, setHistoriqueTraitement] = useState<HistoriqueEntry[]>([])");
A("  const [evolution, setEvolution]               = useState('')");
A("  const [historiqueEvolution, setHistoriqueEvolution] = useState<HistoriqueEntry[]>([])");
A("  const [conseil, setConseil]                   = useState('')");
A("");
A("  useEffect(() => {");
A("    const numId = parseInt(params.id)");
A("    if (MOCK_PATIENTS[numId]) {");
A("      setPatient(MOCK_PATIENTS[numId])");
A("      setAntecedents(MOCK_PATIENTS[numId].antecedents || '')");
A("      setLoading(false); return");
A("    }");
A("    fetch(API + '/patients/' + params.id)");
A("      .then(r => r.json())");
A("      .then(data => { if (data?.id) { setPatient(data); setAntecedents(data.antecedents || '') } setLoading(false) })");
A("      .catch(() => setLoading(false))");
A("  }, [params.id])");
A("");
A("  function enregistrer(texte: string, setTexte: (v:string)=>void, setHisto: React.Dispatch<React.SetStateAction<HistoriqueEntry[]>>) {");
A("    if (!texte.trim()) return");
A("    const { date, heure } = getNow()");
A("    setHisto(prev => [{ date, heure, texte }, ...prev])");
A("    setTexte('')");
A("  }");
A("");
A("  function confirmerValidation() {");
A("    setValide(true); setShowConfirm(false)");
A("    setTimeout(() => router.push('/rapport'), 1500)");
A("  }");
A("");
A("  if (loading) return (");
A("    <AppShell searchPlaceholder=\"Rechercher...\" showSearch={false}>");
A("      <div className=\"py-24 text-center text-on-surface-variant\">");
A("        <span className=\"material-symbols-outlined text-5xl animate-spin\">progress_activity</span>");
A("        <p className=\"mt-4\">Chargement du profil...</p>");
A("      </div>");
A("    </AppShell>");
A("  )");
A("");
A("  if (!patient) return (");
A("    <AppShell searchPlaceholder=\"Rechercher...\" showSearch={false}>");
A("      <div className=\"py-24 text-center text-on-surface-variant\">");
A("        <span className=\"material-symbols-outlined text-5xl\">person_off</span>");
A("        <p className=\"mt-4\">Patient introuvable</p>");
A("        <Link href=\"/patients\" className=\"mt-4 inline-block text-primary hover:underline\">Retour a la liste</Link>");
A("      </div>");
A("    </AppShell>");
A("  )");
A("");
A("  const initials = (patient.prenom?.[0] || '') + (patient.nom?.[0] || '')");
A("  const nomComplet = patient.prenom + ' ' + patient.nom");
A("");
A("  return (");
A("    <AppShell searchPlaceholder=\"Rechercher un patient...\" showSearch={false}>");
A("");
A("      {/* Fil d ariane */}");
A("      <nav className=\"flex items-center gap-2 text-sm text-on-surface-variant mb-6\">");
A("        {from === 'archives' ? (<><Link href=\"/archives\" className=\"hover:text-primary\">Archives</Link><span className=\"material-symbols-outlined text-sm\">chevron_right</span><span className=\"text-on-surface font-semibold\">{nomComplet}</span></>) : from === 'calendrier' ? (<><Link href=\"/calendrier\" className=\"hover:text-primary\">Calendrier</Link><span className=\"material-symbols-outlined text-sm\">chevron_right</span><span className=\"text-on-surface font-semibold\">{nomComplet}</span></>) : from === 'dashboard' ? (<><Link href=\"/\" className=\"hover:text-primary\">Tableau de bord</Link><span className=\"material-symbols-outlined text-sm\">chevron_right</span><span className=\"text-on-surface font-semibold\">{nomComplet}</span></>) : (<><Link href=\"/patients\" className=\"hover:text-primary\">Patients</Link><span className=\"material-symbols-outlined text-sm\">chevron_right</span><span className=\"text-on-surface font-semibold\">{nomComplet}</span></>)}");
A("      </nav>");
A("");
A("      {valide && (");
A("        <div className=\"mb-6 flex items-center gap-3 bg-emerald-50 border border-emerald-200 rounded-xl px-5 py-4\">");
A("          <span className=\"material-symbols-outlined text-emerald-500 text-2xl\">check_circle</span>");
A("          <div>");
A("            <p className=\"font-bold text-emerald-700\">Dossier validé et transmis au rapport !</p>");
A("            <p className=\"text-xs text-emerald-600\">Redirection vers le rapport en cours...</p>");
A("          </div>");
A("        </div>");
A("      )}");
A("");
A("      {/* HEADER PATIENT */}");
A("      <section className=\"bg-gradient-to-r from-teal-600 to-teal-400 rounded-2xl shadow-lg p-6 flex items-start gap-8 mb-6 text-white\">");
A("        <div className=\"relative flex-shrink-0\">");
A("          <div className=\"w-28 h-28 rounded-xl bg-white/20 flex items-center justify-center border-2 border-white/40\">");
A("            <span className=\"text-4xl font-bold text-white font-manrope\">{initials}</span>");
A("          </div>");
A("        </div>");
A("        <div className=\"flex-1\">");
A("          <div className=\"flex justify-between items-start\">");
A("            <div>");
A("              <h2 className=\"text-3xl font-bold text-white font-manrope\">{nomComplet}</h2>");
A("              <p className=\"text-teal-100 font-medium mt-1\">ID: #{patient.numeroDossier || patient.id} · {patient.sexe === 'M' ? 'Homme' : 'Femme'}</p>");
A("            </div>");
A("            <span className={'px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wide ' + (patient.statut==='actif'?'bg-emerald-400 text-white':patient.statut==='archive'?'bg-red-400 text-white':patient.statut==='en_attente'?'bg-amber-400 text-white':'bg-white/30 text-white')}>{patient.statut}</span>");
A("          </div>");
A("          <div className=\"grid grid-cols-2 lg:grid-cols-4 gap-4 mt-5 border-t border-white/20 pt-5\">");
A("            <div>");
A("              <p className=\"text-xs font-semibold text-teal-100 uppercase tracking-widest\">Date de naissance</p>");
A("              <p className=\"text-sm font-bold text-white mt-1\">{patient.dateNaissance || 'N/A'}</p>");
A("            </div>");
A("            <div>");
A("              <p className=\"text-xs font-semibold text-teal-100 uppercase tracking-widest\">Religion</p>");
A("              {!valide ? (");
A("                <input type=\"text\" value={religion} onChange={e => setReligion(e.target.value)}");
A("                  placeholder=\"Ex: Catholique...\"");
A("                  className=\"mt-1 w-full bg-white/20 border border-white/30 rounded-lg px-2 py-1 text-sm text-white placeholder-white/50 focus:outline-none focus:border-white\" />");
A("              ) : (");
A("                <p className=\"text-sm font-bold text-white mt-1\">{religion || '—'}</p>");
A("              )}");
A("            </div>");
A("            <div>");
A("              <p className=\"text-xs font-semibold text-teal-100 uppercase tracking-widest\">Téléphone</p>");
A("              <p className=\"text-sm font-bold text-white mt-1\">{patient.telephone || 'N/A'}</p>");
A("            </div>");
A("            <div>");
A("              <p className=\"text-xs font-semibold text-teal-100 uppercase tracking-widest\">Admission</p>");
A("              <p className=\"text-sm font-bold text-white mt-1\">{patient.dateAdmission || 'N/A'}</p>");
A("            </div>");
A("          </div>");
A("        </div>");
A("      </section>");
A("");
A("      <div className=\"grid grid-cols-12 gap-6\">");
A("        <div className=\"col-span-12 lg:col-span-8 space-y-6\">");
A("");
A("          {/* 1 - SEANCE DU JOUR - teal */}");
A("          <div className={'rounded-xl shadow-sm border p-6 ' + (valide ? 'bg-teal-50 border-teal-200' : 'bg-teal-50 border-teal-200')}>");
A("            <h3 className=\"font-headline-md text-teal-800 flex items-center gap-2 mb-5\">");
A("              <span className=\"material-symbols-outlined text-teal-600\">today</span>");
A("              Séance du jour");
A("              {valide && <span className=\"ml-auto text-xs bg-teal-100 text-teal-700 px-2 py-0.5 rounded-full font-semibold flex items-center gap-1\"><span className=\"material-symbols-outlined text-sm\">lock</span>Validé</span>}");
A("            </h3>");
A("            <div className=\"grid grid-cols-2 gap-4 mb-4\">");
A("              <div>");
A("                <label className=\"text-xs font-bold text-teal-600 uppercase tracking-widest block mb-1\">Heure début</label>");
A("                <input type=\"time\" value={heureDebut} onChange={e => !valide && setHeureDebut(e.target.value)} disabled={valide}");
A("                  className={'w-full px-3 py-2 rounded-lg border text-sm outline-none ' + (valide ? 'bg-teal-100/50 border-teal-200 cursor-not-allowed text-teal-700' : 'bg-white border-teal-200 focus:border-teal-400 focus:ring-1 focus:ring-teal-300')} />");
A("              </div>");
A("              <div>");
A("                <label className=\"text-xs font-bold text-teal-600 uppercase tracking-widest block mb-1\">Heure fin</label>");
A("                <input type=\"time\" value={heureFin} onChange={e => !valide && setHeureFin(e.target.value)} disabled={valide}");
A("                  className={'w-full px-3 py-2 rounded-lg border text-sm outline-none ' + (valide ? 'bg-teal-100/50 border-teal-200 cursor-not-allowed text-teal-700' : 'bg-white border-teal-200 focus:border-teal-400 focus:ring-1 focus:ring-teal-300')} />");
A("              </div>");
A("            </div>");
A("            <div>");
A("              <label className=\"text-xs font-bold text-teal-600 uppercase tracking-widest block mb-2\">Type de séance</label>");
A("              {!valide ? (");
A("                <div className=\"relative inline-block\">");
A("                  <button onClick={() => setShowTypeMenu(v => !v)}");
A("                    className={'flex items-center gap-2 px-4 py-2 rounded-xl border-2 font-semibold text-sm transition-all ' + (typeRdv ? TYPE_COLOR[typeRdv] : 'border-teal-200 text-teal-400 bg-white')}>");
A("                    <span className=\"material-symbols-outlined text-sm\">category</span>");
A("                    {typeRdv ? typeRdv.charAt(0).toUpperCase() + typeRdv.slice(1) : 'Choisir un type'}");
A("                    <span className=\"material-symbols-outlined text-sm\">expand_more</span>");
A("                  </button>");
A("                  {showTypeMenu && (");
A("                    <div className=\"absolute top-full left-0 mt-1 bg-white rounded-xl shadow-xl border border-slate-200 z-20 overflow-hidden\">");
A("                      {TYPES.map(type => (");
A("                        <button key={type} onClick={() => { setTypeRdv(type); setShowTypeMenu(false) }}");
A("                          className={'w-full text-left px-5 py-2.5 text-sm font-semibold capitalize transition-colors hover:opacity-80 ' + TYPE_COLOR[type]}>");
A("                          {type}");
A("                        </button>");
A("                      ))}");
A("                    </div>");
A("                  )}");
A("                </div>");
A("              ) : (");
A("                typeRdv ? <span className={'text-sm font-bold px-4 py-2 rounded-xl border-2 inline-block capitalize ' + TYPE_COLOR[typeRdv]}>{typeRdv}</span> : <span className=\"text-sm text-teal-400 italic\">Non défini</span>");
A("              )}");
A("            </div>");
A("          </div>");
A("");
A("          {/* 2 - MODE ADMISSION - orange */}");
A("          <div className=\"rounded-xl shadow-sm border bg-orange-50 border-orange-200 p-6\">");
A("            <h3 className=\"font-headline-md text-orange-800 flex items-center gap-2 mb-5\">");
A("              <span className=\"material-symbols-outlined text-orange-500\">login</span>");
A("              Mode d'admission");
A("            </h3>");
A("            <div className=\"space-y-4\">");
A("              <div>");
A("                <label className=\"text-xs font-bold text-orange-600 uppercase tracking-widest block mb-1\">Mode d'admission (service envoyeur)</label>");
A("                <textarea value={modeAdmission} onChange={e => !valide && setModeAdmission(e.target.value)} rows={2} disabled={valide}");
A("                  className={'w-full p-3 rounded-lg border text-sm resize-none outline-none ' + (valide ? 'bg-orange-100/50 border-orange-200 cursor-not-allowed' : 'bg-white border-orange-200 focus:border-orange-400 focus:ring-1 focus:ring-orange-200')}");
A("                  placeholder=\"Ex: Service de chirurgie orthopédique...\" />");
A("              </div>");
A("              <div>");
A("                <label className=\"text-xs font-bold text-orange-600 uppercase tracking-widest block mb-1\">Auto référé</label>");
A("                <textarea value={autoRefere} onChange={e => !valide && setAutoRefere(e.target.value)} rows={2} disabled={valide}");
A("                  className={'w-full p-3 rounded-lg border text-sm resize-none outline-none ' + (valide ? 'bg-orange-100/50 border-orange-200 cursor-not-allowed' : 'bg-white border-orange-200 focus:border-orange-400 focus:ring-1 focus:ring-orange-200')}");
A("                  placeholder=\"Préciser si le patient s'est référé lui-même...\" />");
A("              </div>");
A("              <div>");
A("                <label className=\"text-xs font-bold text-orange-600 uppercase tracking-widest block mb-1\">Référé par</label>");
A("                <textarea value={referePar} onChange={e => !valide && setReferePar(e.target.value)} rows={2} disabled={valide}");
A("                  className={'w-full p-3 rounded-lg border text-sm resize-none outline-none ' + (valide ? 'bg-orange-100/50 border-orange-200 cursor-not-allowed' : 'bg-white border-orange-200 focus:border-orange-400 focus:ring-1 focus:ring-orange-200')}");
A("                  placeholder=\"Nom du médecin ou service référent...\" />");
A("              </div>");
A("            </div>");
A("          </div>");
A("");
A("          {/* 3 - OBJECTIF - jaune */}");
A("          <div className=\"rounded-xl shadow-sm border bg-yellow-50 border-yellow-200 p-6\">");
A("            <h3 className=\"font-headline-md text-yellow-800 flex items-center gap-2 mb-5\">");
A("              <span className=\"material-symbols-outlined text-yellow-600\">flag</span>");
A("              Objectif présempteur");
A("            </h3>");
A("            <div>");
A("              <label className=\"text-xs font-bold text-yellow-600 uppercase tracking-widest block mb-1\">Objectif</label>");
A("              <textarea value={objectif} onChange={e => !valide && setObjectif(e.target.value)} rows={3} disabled={valide}");
A("                className={'w-full p-3 rounded-lg border text-sm resize-none outline-none ' + (valide ? 'bg-yellow-100/50 border-yellow-200 cursor-not-allowed' : 'bg-white border-yellow-200 focus:border-yellow-400 focus:ring-1 focus:ring-yellow-200')}");
A("                placeholder=\"Décrire l'objectif thérapeutique présempteur...\" />");
A("            </div>");
A("          </div>");
A("");
A("          {/* 4 - BILAN KINE - violet */}");
A("          <div className=\"rounded-xl shadow-sm border bg-purple-50 border-purple-200 p-6\">");
A("            <h3 className=\"font-headline-md text-purple-800 flex items-center gap-2 mb-5\">");
A("              <span className=\"material-symbols-outlined text-purple-600\">fact_check</span>");
A("              Bilan kinésithérapique");
A("            </h3>");
A("            <div className=\"space-y-4\">");
A("              {[");
A("                { label: 'Antécédents', value: antecedents, set: setAntecedents, ph: 'Antécédents médicaux, chirurgicaux, familiaux...' },");
A("                { label: 'Histoire de la maladie', value: historieMaladie, set: setHistorieMaladie, ph: 'Décrire l'évolution de la maladie depuis le début...' },");
A("                { label: 'Bilan fonctionnel', value: bilanFonctionnel, set: setBilanFonctionnel, ph: 'Évaluation des capacités fonctionnelles du patient...' },");
A("                { label: 'Bilan d'incapacité', value: bilanIncapacite, set: setBilanIncapacite, ph: 'Évaluation des incapacités et limitations...' },");
A("              ].map(f => (");
A("                <div key={f.label}>");
A("                  <label className=\"text-xs font-bold text-purple-600 uppercase tracking-widest block mb-1\">{f.label}</label>");
A("                  <textarea value={f.value} onChange={e => !valide && f.set(e.target.value)} rows={3} disabled={valide}");
A("                    className={'w-full p-3 rounded-lg border text-sm resize-none outline-none ' + (valide ? 'bg-purple-100/50 border-purple-200 cursor-not-allowed' : 'bg-white border-purple-200 focus:border-purple-400 focus:ring-1 focus:ring-purple-200')}");
A("                    placeholder={valide ? '' : f.ph} />");
A("                </div>");
A("              ))}");
A("            </div>");
A("          </div>");
A("");
A("          {/* 5 - DIAGNOSTIC KINE - bleu */}");
A("          <div className=\"rounded-xl shadow-sm border bg-blue-50 border-blue-200 p-6\">");
A("            <h3 className=\"font-headline-md text-blue-800 flex items-center gap-2 mb-5\">");
A("              <span className=\"material-symbols-outlined text-blue-600\">diagnosis</span>");
A("              Diagnostic kinésithérapique");
A("            </h3>");
A("            <div>");
A("              <label className=\"text-xs font-bold text-blue-600 uppercase tracking-widest block mb-1\">Diagnostic kinésithérapique</label>");
A("              <textarea value={diagnosticKine} onChange={e => !valide && setDiagnosticKine(e.target.value)} rows={3} disabled={valide}");
A("                className={'w-full p-3 rounded-lg border text-sm resize-none outline-none ' + (valide ? 'bg-blue-100/50 border-blue-200 cursor-not-allowed' : 'bg-white border-blue-200 focus:border-blue-400 focus:ring-1 focus:ring-blue-200')}");
A("                placeholder=\"Diagnostic établi par le kinésithérapeute...\" />");
A("            </div>");
A("          </div>");
A("");
A("          {/* 6 - TRAITEMENT - vert */}");
A("          <SectionHistorique label=\"Traitement\" icon=\"vaccines\"");
A("            value={traitement} onChange={setTraitement}");
A("            historique={historiqueTraitement}");
A("            onEnregistrer={() => enregistrer(traitement, setTraitement, setHistoriqueTraitement)}");
A("            bgClass=\"bg-green-50\" borderClass=\"border-green-200\" titleColor=\"text-green-800\"");
A("            histoBg=\"bg-green-100\" histoBorder=\"border-green-200\" histoTimeColor=\"text-green-600\"");
A("            locked={valide} />");
A("");
A("          {/* 7 - EVOLUTION - emerald */}");
A("          <SectionHistorique label=\"Évolution et suivi\" icon=\"trending_up\"");
A("            value={evolution} onChange={setEvolution}");
A("            historique={historiqueEvolution}");
A("            onEnregistrer={() => enregistrer(evolution, setEvolution, setHistoriqueEvolution)}");
A("            bgClass=\"bg-emerald-50\" borderClass=\"border-emerald-200\" titleColor=\"text-emerald-800\"");
A("            histoBg=\"bg-emerald-100\" histoBorder=\"border-emerald-200\" histoTimeColor=\"text-emerald-600\"");
A("            locked={valide} />");
A("");
A("          {/* 8 - CONSEIL - amber */}");
A("          <div className=\"rounded-xl shadow-sm border bg-amber-50 border-amber-200 p-6\">");
A("            <h3 className=\"font-headline-md text-amber-800 flex items-center gap-2 mb-4\">");
A("              <span className=\"material-symbols-outlined text-amber-600\">lightbulb</span>");
A("              Conseil");
A("              {valide && <span className=\"ml-auto text-xs bg-amber-100 text-amber-700 px-2 py-0.5 rounded-full font-semibold flex items-center gap-1\"><span className=\"material-symbols-outlined text-sm\">lock</span>Validé</span>}");
A("            </h3>");
A("            <div>");
A("              <label className=\"text-xs font-bold text-amber-600 uppercase tracking-widest block mb-1\">Conseils au patient</label>");
A("              <textarea value={conseil} onChange={e => !valide && setConseil(e.target.value)} rows={4} disabled={valide}");
A("                className={'w-full p-3 rounded-lg border text-sm resize-none outline-none ' + (valide ? 'bg-amber-100/50 border-amber-200 cursor-not-allowed' : 'bg-white border-amber-200 focus:border-amber-400 focus:ring-1 focus:ring-amber-200')}");
A("                placeholder=\"Conseils hygiéno-diététiques, posturaux, exercices à domicile...\" />");
A("            </div>");
A("          </div>");
A("");
A("          {/* BOUTON VALIDER */}");
A("          {!valide && (");
A("            <div className=\"bg-white rounded-xl shadow-sm border border-slate-200 p-6 flex flex-col items-center gap-3\">");
A("              <p className=\"text-sm text-on-surface-variant text-center\">Une fois validé, le dossier sera transmis au rapport et ne pourra plus être modifié.</p>");
A("              <button onClick={() => setShowConfirm(true)}");
A("                className=\"flex items-center gap-2 px-8 py-3 rounded-xl bg-emerald-500 text-white font-bold text-base shadow-lg hover:bg-emerald-600 transition-all\">");
A("                <span className=\"material-symbols-outlined\">check_circle</span>");
A("                Valider le dossier");
A("              </button>");
A("            </div>");
A("          )}");
A("");
A("        </div>");
A("");
A("        {/* COLONNE DROITE */}");
A("        <div className=\"col-span-12 lg:col-span-4 space-y-6\">");
A("          <div className=\"bg-white rounded-xl shadow-sm border border-slate-200 p-6\">");
A("            <h4 className=\"font-title-sm text-on-surface mb-4\">Actions rapides</h4>");
A("            <div className=\"space-y-3\">");
A("              <button className=\"w-full flex items-center gap-3 px-4 py-3 rounded-lg bg-primary text-white font-semibold text-sm hover:opacity-90 transition-all\">");
A("                <span className=\"material-symbols-outlined text-lg\">event_available</span>");
A("                Nouveau rendez-vous");
A("              </button>");
A("              <button className=\"w-full flex items-center gap-3 px-4 py-3 rounded-lg border border-slate-200 text-on-surface font-semibold text-sm hover:bg-slate-50 transition-all\">");
A("                <span className=\"material-symbols-outlined text-lg\">edit</span>");
A("                Modifier le profil");
A("              </button>");
A("              {from === 'archives' ? (");
A("                <Link href=\"/archives\" className=\"w-full flex items-center gap-3 px-4 py-3 rounded-lg border border-slate-200 text-on-surface font-semibold text-sm hover:bg-slate-50 transition-all\">");
A("                  <span className=\"material-symbols-outlined text-lg\">arrow_back</span>Retour aux archives");
A("                </Link>");
A("              ) : from === 'calendrier' ? (");
A("                <Link href=\"/calendrier\" className=\"w-full flex items-center gap-3 px-4 py-3 rounded-lg border border-slate-200 text-on-surface font-semibold text-sm hover:bg-slate-50 transition-all\">");
A("                  <span className=\"material-symbols-outlined text-lg\">arrow_back</span>Retour au calendrier");
A("                </Link>");
A("              ) : from === 'dashboard' ? (");
A("                <Link href=\"/\" className=\"w-full flex items-center gap-3 px-4 py-3 rounded-lg border border-slate-200 text-on-surface font-semibold text-sm hover:bg-slate-50 transition-all\">");
A("                  <span className=\"material-symbols-outlined text-lg\">arrow_back</span>Retour au tableau de bord");
A("                </Link>");
A("              ) : (");
A("                <Link href=\"/patients\" className=\"w-full flex items-center gap-3 px-4 py-3 rounded-lg border border-slate-200 text-on-surface font-semibold text-sm hover:bg-slate-50 transition-all\">");
A("                  <span className=\"material-symbols-outlined text-lg\">arrow_back</span>Retour a la liste");
A("                </Link>");
A("              )}");
A("            </div>");
A("          </div>");
A("");
A("          <div className=\"bg-gradient-to-br from-teal-600 to-teal-400 rounded-xl shadow-lg p-6 text-white relative overflow-hidden\">");
A("            <div className=\"relative z-10\">");
A("              <h4 className=\"font-bold text-lg mb-2\">Dossier Patient</h4>");
A("              <p className=\"text-teal-100 text-sm mb-1\">N° {patient.numeroDossier || patient.id}</p>");
A("              <p className=\"text-teal-100 text-sm mb-4\">Admission : {patient.dateAdmission || 'N/A'}</p>");
A("              <div className={'inline-block px-3 py-1 rounded-full text-xs font-bold uppercase ' + (patient.statut==='actif'?'bg-emerald-400 text-white':patient.statut==='archive'?'bg-red-400 text-white':'bg-amber-400 text-white')}>");
A("                {patient.statut}");
A("              </div>");
A("            </div>");
A("            <span className=\"material-symbols-outlined absolute -right-4 -bottom-4 text-8xl text-white/10 rotate-12\">folder_shared</span>");
A("          </div>");
A("        </div>");
A("      </div>");
A("");
A("      {/* MODAL CONFIRMATION */}");
A("      {showConfirm && (");
A("        <div className=\"fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm\">");
A("          <div className=\"bg-surface rounded-2xl shadow-2xl p-8 max-w-sm w-full mx-4 text-center\">");
A("            <div className=\"w-16 h-16 bg-emerald-50 rounded-full flex items-center justify-center mx-auto mb-4\">");
A("              <span className=\"material-symbols-outlined text-emerald-500 text-3xl\">check_circle</span>");
A("            </div>");
A("            <h3 className=\"text-lg font-bold text-on-surface mb-2\">Confirmer la validation</h3>");
A("            <p className=\"text-sm text-on-surface-variant mb-6\">Une fois validé, le dossier sera <strong>verrouillé</strong> et transmis automatiquement au rapport. Cette action est <strong>irréversible</strong>.</p>");
A("            <div className=\"flex gap-3\">");
A("              <button onClick={() => setShowConfirm(false)}");
A("                className=\"flex-1 px-4 py-2.5 rounded-lg border border-outline-variant text-on-surface font-semibold text-sm hover:bg-surface-container-low\">");
A("                Annuler");
A("              </button>");
A("              <button onClick={confirmerValidation}");
A("                className=\"flex-1 px-4 py-2.5 rounded-lg bg-emerald-500 text-white font-semibold text-sm hover:bg-emerald-600 shadow-sm\">");
A("                Confirmer");
A("              </button>");
A("            </div>");
A("          </div>");
A("        </div>");
A("      )}");
A("");
A("    </AppShell>");
A("  )");
A("}");

fs.writeFileSync('D:/chu_kine/projet_frontend/src/app/patients/[id]/page.tsx', lines.join('\n'), {encoding:'utf8'});
console.log('patients/[id]/page.tsx - version v5 avec couleurs et corrections !');
