const fs = require('fs');
const lines = [];
const A = (s) => lines.push(s);

A("'use client'");
A("");
A("import { useState, useMemo } from 'react'");
A("import Link from 'next/link'");
A("import AppShell from '@/components/layout/AppShell'");
A("import { useLanguage } from '@/context/LanguageContext'");
A("");
A("interface Patient {");
A("  id: number; numeroDossier: string; nom: string; prenom: string");
A("  dateNaissance: string; sexe: string; diagnostic: string");
A("  statut: string; dateAdmission: string; dateDerniereVisite: string");
A("}");
A("");
A("const MOCK_PATIENTS: Patient[] = [");
A("  { id: 1, numeroDossier: 'P-2024-001', nom: 'Rakoto', prenom: 'Jean', dateNaissance: '1985-03-12', sexe: 'M', diagnostic: 'Rupture LCA genou droit - post-operatoire', statut: 'actif', dateAdmission: '2024-04-12', dateDerniereVisite: '2024-06-08' },");
A("  { id: 2, numeroDossier: 'P-2024-002', nom: 'Rabe', prenom: 'Marie', dateNaissance: '1992-07-23', sexe: 'F', diagnostic: 'Tendinite calcifiante epaule droite', statut: 'actif', dateAdmission: '2024-04-18', dateDerniereVisite: '2024-06-05' },");
A("  { id: 3, numeroDossier: 'P-2024-003', nom: 'Andria', prenom: 'Paul', dateNaissance: '1978-11-08', sexe: 'M', diagnostic: 'Entorse cheville gauche grade 2', statut: 'actif', dateAdmission: '2024-04-22', dateDerniereVisite: '2024-06-09' },");
A("  { id: 4, numeroDossier: 'P-2024-004', nom: 'Rasoa', prenom: 'Lala', dateNaissance: '1965-05-30', sexe: 'F', diagnostic: 'Arthrose lombaire chronique', statut: 'en_attente', dateAdmission: '2024-05-02', dateDerniereVisite: '' },");
A("  { id: 5, numeroDossier: 'P-2024-005', nom: 'Rakotonirina', prenom: 'Zo', dateNaissance: '2001-09-15', sexe: 'F', diagnostic: 'Scoliose thoracique - suivi', statut: 'inactif', dateAdmission: '2024-03-10', dateDerniereVisite: '2024-05-28' },");
A("  { id: 6, numeroDossier: 'P-2024-006', nom: 'Randriamihaingo', prenom: 'Tiana', dateNaissance: '1988-02-20', sexe: 'F', diagnostic: 'Paralysie faciale peripherique droite', statut: 'en_attente', dateAdmission: '2024-06-08', dateDerniereVisite: '' },");
A("  { id: 7, numeroDossier: 'P-2024-007', nom: 'Rakotondrabe', prenom: 'Hery', dateNaissance: '1970-12-01', sexe: 'M', diagnostic: 'Hernie discale L4-L5', statut: 'archive', dateAdmission: '2024-01-15', dateDerniereVisite: '2024-03-20' },");
A("  { id: 8, numeroDossier: 'P-2024-008', nom: 'Andriantsoa', prenom: 'Noro', dateNaissance: '1995-04-18', sexe: 'F', diagnostic: 'Tendinopathie achilleenne', statut: 'archive', dateAdmission: '2024-02-10', dateDerniereVisite: '2024-04-05' },");
A("  { id: 101, numeroDossier: 'P-2024-101', nom: 'Jenkins', prenom: 'Sarah', dateNaissance: '1990-05-14', sexe: 'F', diagnostic: 'Suivi Post-operatoire Genou', statut: 'actif', dateAdmission: '2024-03-01', dateDerniereVisite: '2024-06-10' },");
A("  { id: 102, numeroDossier: 'P-2024-102', nom: 'Chen', prenom: 'Michael', dateNaissance: '1983-11-22', sexe: 'M', diagnostic: 'Consultation Initial Dos', statut: 'en_attente', dateAdmission: '2024-06-09', dateDerniereVisite: '' },");
A("  { id: 103, numeroDossier: 'P-2024-103', nom: 'Rodriguez', prenom: 'Elena', dateNaissance: '1981-03-08', sexe: 'F', diagnostic: 'Reeducation Epaule', statut: 'actif', dateAdmission: '2024-04-15', dateDerniereVisite: '2024-06-12' },");
A("]");
A("");
A("export default function PatientsPage() {");
A("  const { t } = useLanguage()");
A("  const [patients, setPatients] = useState<Patient[]>(MOCK_PATIENTS)");
A("  const [search, setSearch]     = useState('')");
A("  const [confirmId, setConfirmId] = useState<number | null>(null)");
A("");
A("  const filtered = useMemo(() => {");
A("    let list = patients.filter(p => p.statut !== 'archive')");
A("    const s = search.trim().toLowerCase()");
A("    if (s) list = list.filter(p =>"); 
A("      (p.prenom + ' ' + p.nom).toLowerCase().includes(s) ||");
A("      p.numeroDossier?.toLowerCase().includes(s) ||");
A("      p.diagnostic?.toLowerCase().includes(s)");
A("    )");
A("    return list");
A("  }, [search, patients])");
A("");
A("  function archiver(id: number) {");
A("    setPatients(prev => prev.map(p => p.id === id ? { ...p, statut: 'archive' } : p))");
A("    setConfirmId(null)");
A("  }");
A("");
A("  const nbActifs = patients.filter(p => p.statut !== 'archive').length");
A("");
A("  return (");
A("    <AppShell searchPlaceholder={t('pat_rechercherPlaceholder')} showSearch={false}>");
A("      <div className=\"flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4 mb-6\">");
A("        <div>");
A("          <h2 className=\"text-2xl font-bold text-on-surface font-manrope\">{t('pat_titre')}</h2>");
A("          <p className=\"text-sm text-on-surface-variant mt-1\">{nbActifs} {t('pat_enregistres')}</p>");
A("        </div>");
A("        <Link href=\"/patients/nouveau\" className=\"btn-primary\">");
A("          <span className=\"material-symbols-outlined text-lg\">person_add</span>");
A("          {t('pat_nouveauPatient')}");
A("        </Link>");
A("      </div>");
A("");
A("      {/* BARRE DE RECHERCHE */}");
A("      <div className=\"flex flex-col sm:flex-row gap-3 mb-6\">");
A("        <div className=\"flex items-center gap-3 bg-surface border border-outline-variant px-4 py-2 rounded-lg flex-1 max-w-md\">");
A("          <span className=\"material-symbols-outlined text-on-surface-variant text-lg\">search</span>");
A("          <input type=\"text\" placeholder={t('pat_rechercherPlaceholder')} value={search}");
A("            onChange={e => setSearch(e.target.value)}");
A("            className=\"bg-transparent border-none focus:outline-none text-sm w-full text-on-surface placeholder:text-on-surface-variant\" />");
A("          {search && (");
A("            <button onClick={() => setSearch('')} className=\"text-on-surface-variant hover:text-red-500 transition-colors flex-shrink-0\">");
A("              <span className=\"material-symbols-outlined text-lg\">close</span>");
A("            </button>");
A("          )}");
A("        </div>");
A("      </div>");
A("");
A("      {/* TABLEAU */}");
A("      <div className=\"bg-surface rounded-xl border border-outline-variant shadow-sm overflow-hidden\">");
A("        <div className=\"overflow-x-auto\">");
A("          <table className=\"w-full\">");
A("            <thead>");
A("              <tr className=\"border-b border-outline-variant bg-surface-container-low/50\">");
A("                <th className=\"table-header\">{t('pat_colDossier')}</th>");
A("                <th className=\"table-header\">{t('pat_colPatient')}</th>");
A("                <th className=\"table-header\">{t('pat_colDiagnostic')}</th>");
A("                <th className=\"table-header\">{t('pat_colDerniereVisite')}</th>");
A("                <th className=\"table-header text-center\">{t('pat_colArchive')}</th>");
A("                <th className=\"table-header w-10\"></th>");
A("              </tr>");
A("            </thead>");
A("            <tbody>");
A("              {filtered.map(p => (");
A("                <tr key={p.id} className=\"hover:bg-surface-container-low/50 transition-colors\">");
A("                  <td className=\"table-cell\">");
A("                    <span className=\"text-xs font-mono text-primary font-semibold\">{p.numeroDossier || '-'}</span>");
A("                  </td>");
A("                  <td className=\"table-cell\">");
A("                    <Link href={'/patients/' + p.id} className=\"hover:underline\">");
A("                      <p className=\"font-semibold text-on-surface\">{p.prenom} {p.nom}</p>");
A("                      <p className=\"text-xs text-on-surface-variant\">{p.dateNaissance} - {p.sexe === 'M' ? t('cal_homme') : t('cal_femme')}</p>");
A("                    </Link>");
A("                  </td>");
A("                  <td className=\"table-cell\">");
A("                    <p className=\"text-sm text-on-surface max-w-[200px] truncate\">{p.diagnostic || '-'}</p>");
A("                  </td>");
A("                  <td className=\"table-cell text-xs text-on-surface-variant\">{p.dateDerniereVisite || '-'}</td>");
A("                  <td className=\"table-cell text-center\">");
A("                    <button onClick={() => setConfirmId(p.id)}");
A("                      className=\"inline-flex items-center gap-1 px-3 py-1.5 rounded-lg bg-amber-50 text-amber-700 text-xs font-semibold hover:bg-amber-100 transition-colors border border-amber-200\">");
A("                      <span className=\"material-symbols-outlined text-sm\">inventory_2</span>");
A("                      {t('pat_btnArchiver')}");
A("                    </button>");
A("                  </td>");
A("                  <td className=\"table-cell\">");
A("                    <Link href={'/patients/' + p.id} className=\"material-symbols-outlined text-on-surface-variant hover:text-primary transition-colors text-lg\">chevron_right</Link>");
A("                  </td>");
A("                </tr>");
A("              ))}");
A("            </tbody>");
A("          </table>");
A("          {filtered.length === 0 && (");
A("            <div className=\"py-12 text-center text-on-surface-variant\">");
A("              <span className=\"material-symbols-outlined text-4xl mb-2\">search_off</span>");
A("              <p className=\"mb-4\">{t('pat_aucunTrouve')}</p>");
A("              <button onClick={() => setSearch('')}");
A("                className=\"px-4 py-2 rounded-lg bg-primary text-white text-sm font-semibold hover:opacity-90\">");
A("                {t('pat_voirTousPatients')}");
A("              </button>");
A("            </div>");
A("          )}");
A("        </div>");
A("      </div>");
A("");
A("      {confirmId !== null && (");
A("        <div className=\"fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm\">");
A("          <div className=\"bg-surface rounded-2xl shadow-2xl p-8 max-w-sm w-full mx-4 text-center\">");
A("            <div className=\"w-16 h-16 bg-amber-50 rounded-full flex items-center justify-center mx-auto mb-4\">");
A("              <span className=\"material-symbols-outlined text-amber-500 text-3xl\">inventory_2</span>");
A("            </div>");
A("            <h3 className=\"text-lg font-bold text-on-surface mb-2\">{t('pat_modalTitre')}</h3>");
A("            <p className=\"text-sm text-on-surface-variant mb-6\">{t('pat_modalDesc')}</p>");
A("            <div className=\"flex gap-3\">");
A("              <button onClick={() => setConfirmId(null)} className=\"flex-1 px-4 py-2.5 rounded-lg border border-outline-variant text-on-surface font-semibold text-sm hover:bg-surface-container-low\">");
A("                {t('pat_annuler')}");
A("              </button>");
A("              <button onClick={() => archiver(confirmId)} className=\"flex-1 px-4 py-2.5 rounded-lg bg-amber-500 text-white font-semibold text-sm hover:bg-amber-600 shadow-sm\">");
A("                {t('pat_confirmer')}");
A("              </button>");
A("            </div>");
A("          </div>");
A("        </div>");
A("      )}");
A("    </AppShell>");
A("  )");
A("}");

fs.writeFileSync('D:/chu_kine/projet_frontend/src/app/patients/page.tsx', lines.join('\n'), {encoding:'utf8'});
console.log('patients/page.tsx corrige avec succes !');
