const fs = require('fs');
const lines = [];
const A = (s) => lines.push(s);

A("'use client'");
A("");
A("import { useState, useEffect } from 'react'");
A("import AppShell from '@/components/layout/AppShell'");
A("import { useLanguage } from '@/context/LanguageContext'");
A("");
A("type Theme = 'clair' | 'sombre' | 'systeme'");
A("");
A("export default function ParametresPage() {");
A("  const { langue, setLangue, t } = useLanguage()");
A("  const [theme, setTheme] = useState<Theme>(() => (typeof window !== 'undefined' ? (localStorage.getItem('theme') as Theme) || 'clair' : 'clair'))");
A("  const [toast, setToast] = useState('')");
A("");
A("  useEffect(() => {");
A("    const root = document.documentElement");
A("    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches");
A("    const isDark = theme === 'sombre' || (theme === 'systeme' && prefersDark)");
A("    isDark ? root.classList.add('dark') : root.classList.remove('dark')");
A("    localStorage.setItem('theme', theme)");
A("    showToast(t('par_themeApplique') + ' : ' + (theme === 'clair' ? t('par_clair') : theme === 'sombre' ? t('par_sombre') : t('par_systeme')))");
A("  }, [theme])");
A("");
A("  function showToast(msg: string) {");
A("    setToast(msg)");
A("    setTimeout(() => setToast(''), 2500)");
A("  }");
A("");
A("  function changerLangue(val: 'fr' | 'mg' | 'en') {");
A("    setLangue(val)");
A("    showToast(val === 'fr' ? '[FR] Francais selectionne' : val === 'mg' ? '[MG] Malagasy voafidy' : '[EN] English selected')");
A("  }");
A("");
A("  return (");
A("    <AppShell searchPlaceholder=\"Rechercher...\">");
A("");
A("      {toast && (");
A("        <div className=\"fixed top-6 right-6 z-50 bg-surface-container-low text-on-surface text-sm font-semibold px-5 py-3 rounded-xl shadow-2xl border border-outline-variant flex items-center gap-2\">");
A("          <span className=\"material-symbols-outlined text-base text-green-400\">check_circle</span>");
A("          {toast}");
A("        </div>");
A("      )}");
A("");
A("      <div className=\"mb-8\">");
A("        <h2 className=\"font-headline-md text-on-surface\">{t('par_titre')}</h2>");
A("        <p className=\"font-body-lg text-on-surface-variant\">{t('par_sousTitre')}</p>");
A("      </div>");
A("");
A("      <div className=\"max-w-2xl space-y-6\">");
A("");
A("        <section className=\"bg-surface rounded-xl border border-outline-variant shadow-sm overflow-hidden\">");
A("          <div className=\"px-6 py-4 border-b border-outline-variant bg-surface-container-low/50 flex items-center gap-3\">");
A("            <span className=\"material-symbols-outlined text-primary\">palette</span>");
A("            <h3 className=\"font-title-sm text-on-surface\">{t('par_theme')}</h3>");
A("          </div>");
A("          <div className=\"p-6\">");
A("            <p className=\"text-sm text-on-surface-variant mb-4\">{t('par_themeDesc')}</p>");
A("            <div className=\"grid grid-cols-3 gap-3\">");
A("              {([");
A("                { value: 'clair' as Theme, icon: 'light_mode', label: t('par_clair') },");
A("                { value: 'sombre' as Theme, icon: 'dark_mode', label: t('par_sombre') },");
A("                { value: 'systeme' as Theme, icon: 'contrast', label: t('par_systeme') },");
A("              ]).map((opt) => (");
A("                <button key={opt.value} onClick={() => setTheme(opt.value)}");
A("                  className={\"flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all duration-200 \" + (theme === opt.value ? \"border-primary bg-teal-50 text-primary\" : \"border-outline-variant text-on-surface-variant hover:border-outline hover:bg-surface-container-low\")}>");
A("                  <span className=\"material-symbols-outlined text-2xl\">{opt.icon}</span>");
A("                  <span className=\"text-sm font-semibold\">{opt.label}</span>");
A("                  {theme === opt.value && <span className=\"material-symbols-outlined text-base text-primary\">check_circle</span>}");
A("                </button>");
A("              ))}");
A("            </div>");
A("            <div className={\"mt-4 rounded-xl p-4 border flex items-center gap-3 transition-all duration-300 \" + (theme === 'sombre' ? \"bg-surface-container-low border-outline-variant\" : theme === 'systeme' ? \"bg-surface-container-low border-outline-variant\" : \"bg-surface border-outline-variant\")}>");
A("              <span className={\"material-symbols-outlined text-2xl \" + (theme === 'sombre' ? \"text-on-surface\" : \"text-on-surface-variant\")}>");
A("                {theme === 'clair' ? 'light_mode' : theme === 'sombre' ? 'dark_mode' : 'contrast'}");
A("              </span>");
A("              <div>");
A("                <p className=\"text-sm font-semibold text-on-surface\">{t('par_themeApplique')}</p>");
A("                <p className=\"text-xs text-on-surface-variant\">{theme === 'clair' ? t('par_clair') : theme === 'sombre' ? t('par_sombre') : t('par_systeme')}</p>");
A("              </div>");
A("            </div>");
A("          </div>");
A("        </section>");
A("");
A("        <section className=\"bg-surface rounded-xl border border-outline-variant shadow-sm overflow-hidden\">");
A("          <div className=\"px-6 py-4 border-b border-outline-variant bg-surface-container-low/50 flex items-center gap-3\">");
A("            <span className=\"material-symbols-outlined text-primary\">language</span>");
A("            <h3 className=\"font-title-sm text-on-surface\">{t('par_langue')}</h3>");
A("          </div>");
A("          <div className=\"p-6\">");
A("            <p className=\"text-sm text-on-surface-variant mb-4\">{t('par_langueDesc')}</p>");
A("            <div className=\"space-y-2\">");
A("              {([");
A("                { value: 'fr' as const, flag: 'FR', label: t('par_francais'), sub: t('par_langueParDefaut'), bg: 'bg-blue-100 text-blue-700' },");
A("                { value: 'mg' as const, flag: 'MG', label: t('par_malagasy'), sub: t('par_fitenyMalagasy'), bg: 'bg-red-100 text-red-700' },");
A("                { value: 'en' as const, flag: 'EN', label: t('par_english'), sub: t('par_englishLanguage'), bg: 'bg-surface-container-low text-on-surface-variant' },");
A("              ]).map((opt) => (");
A("                <button key={opt.value} onClick={() => changerLangue(opt.value)}");
A("                  className={\"w-full flex items-center gap-4 px-4 py-3 rounded-xl border-2 transition-all duration-200 text-left \" + (langue === opt.value ? \"border-primary bg-teal-50\" : \"border-outline-variant hover:border-outline hover:bg-surface-container-low\")}>");
A("                  <div className={\"w-10 h-10 rounded-lg flex items-center justify-center font-bold text-xs flex-shrink-0 \" + opt.bg}>{opt.flag}</div>");
A("                  <div className=\"flex-1\">");
A("                    <p className={\"text-sm font-semibold \" + (langue === opt.value ? \"text-primary\" : \"text-on-surface\")}>{opt.label}</p>");
A("                    <p className=\"text-xs text-on-surface-variant\">{opt.sub}</p>");
A("                  </div>");
A("                  {langue === opt.value && <span className=\"material-symbols-outlined text-primary text-xl\">check_circle</span>}");
A("                </button>");
A("              ))}");
A("            </div>");
A("          </div>");
A("        </section>");
A("");
A("      </div>");
A("");
A("    </AppShell>");
A("  )");
A("}");

fs.writeFileSync('D:/chu_kine/projet_frontend/src/app/parametres/page.tsx', lines.join('\n'), {encoding:'utf8'});
console.log('parametres/page.tsx mis a jour : sections Aide et Deconnexion supprimees !');
